### ISSUE TITLE
Incorrect paginate length when no results returned

### ISSUE THREAD

**Issue by JeffBeltran** [teamtnt/laravel-scout-tntsearch-driver#100]
For whatever reason when the paginate function is called on the search and the result is 0 it will show as 1 under total for the lengthAwarePaginator. But if i call the same paginate on a normal query that returns zero will return what is espected...

I ran a few tests but here is the example that i used (the Employee table was truncated so there are no records in the DB)

```

$results = Employee::search($request->userSearchTerm)->paginate(15);
dump($results);

$testSearch = Employee::search($request->userSearchTerm)->get();
$allEmployees = Employee::where('deleted_at', null)->paginate(15);
dump($testSearch);
dump($allEmployees);
dd('stop');

```

That will spit out 

```
LengthAwarePaginator {#894
  #total: 1
  #lastPage: 1
  #items: Collection {#893
    #items: []
  }
  #perPage: 15
  #currentPage: 1
  #path: "http://ocas.dev/sessionkiosk/search"
  #query: array:1 [
    "query" => "bob"
  ]
  #fragment: null
  #pageName: "page"
}

Collection {#889
  #items: []
}

LengthAwarePaginator {#861
  #total: 0
  #lastPage: 0
  #items: Collection {#879
    #items: []
  }
  #perPage: 15
  #currentPage: 1
  #path: "http://ocas.dev/sessionkiosk/search"
  #query: []
  #fragment: null
  #pageName: "page"
}

"stop"
```

So im not sure if i'm doing it incorrectly or if it's a bug, any help would be appreciated

**Comment by BillRiess** [comment]
The pagination is also thrown off if you use a where clause on the search:
`User::search($query)->where('organization_id', $organization->getId())->paginate();`
will return the pagination before the where clause is applied, giving you page numbers on empty results.

**Comment by jonathandey** [comment]
@BillRiess I'm having a problem that I think is somewhat related to yours. The method `getTotalCount` returns the number of results matching your search query in the tntsearch db. When in actual fact we want the total number of items the engine's `map` method returns.

I think I have a solution. I'll be forking the repo today in an attempt to resolve this.

**Comment by michaelklopf** [comment]
Well, issue #128 is closed but the last comment says it needs more work. I have the same problem, that pagination is not correct, because we apply a where clause with the search. Gives me, for example, 22 results instead of 3.

**Comment by nticaric** [comment]
The pagination is not broken, the thing is that TNTSearch is field agnostic so the `where` clause doesn't work

**Comment by michaelklopf** [comment]
Thank you for that information, but what would you do, to limit the search results to a specific id. For example multiple companies are searched through, but I only want the results of one company.

**Comment by nticaric** [comment]
What you can do is filter through the returned collection and only return the wanted company

**Comment by nticaric** [comment]
I have a feeling that you don't need full text search support at all if you're searching by document id and company id.

There are many solution depending on your particular use case. Depending on how many companies you have, you could create an index for each one

**Comment by BillRiess** [comment]
But what about when you need to search text and still paginate? I still
feel this isn't working quite right.

**Comment by nticaric** [comment]
@BillRiess The pagination works correctly, but the where clause does not, because TNTSearch doesn't distinguish fields

Simply return all the results, filter them by let's say company id, and create a paginator. Performance wise it's the same, because TNTSearch does exactly this when you call the paginate() method

**Comment by michaelklopf** [comment]
Ok, what helped here, was to do the following.

Instead of this:
`$searchResult = Documents::search($request->document_id);`

I got the recommendation to do this:
`$keys = Documents::search($request->document_id)->get()->pluck('id');`
`$searchResult = $searchResult->whereIn('id', $keys);`

With this your `$searchResult` will be an Illuminate\Database\Eloquent\Builder, instead of Illuminate\Database\Eloquent\Collection.

This makes this work:
`$searchResult = $searchResult->where('company_id', $request->company);`

and also this:
`$paginator = $searchResult->paginate(10);`

**Comment by nticaric** [comment]
Why do you even use search if you can do:

```php
return Documents::where("document_id", $request->document_id)->paginate(15);

**Comment by michaelklopf** [comment]
When I don't use search, I can't profit from the fuzzy search.
