### ISSUE TITLE
Insertion of 1 record in a 3M records index goes timeout

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [teamtnt/laravel-scout-tntsearch-driver#105]
Hi,
 I'm on Laravel 5.4 (migrated from 5.2) and using Scout and TNTSearch.
and teamtnt/laravel-scout-tntsearch-driver: v3.0.0 and laravel/scout: version: v3.0.7

I've a table with ~3M rows and created and index with tntsearch:import (~1,5G). 

I can search and get results from the index in a normal time (~1s).

The problem comes out when I try to save an index-related model, with

$model->save();

it starts thinking and after 30s my Apache enacts timeout with following error:

Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /Users/jack/Documents/VirtualHosts/project/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php on line 546

    public function prepareAndExecuteStatement($query, $params = [])
    {
        $statemnt = $this->index->prepare($query);
        foreach ($params as $param) {
            $statemnt->bindParam($param['key'], $param['value']);
        }
        $statemnt->execute();  //<--- here
        return $statemnt;
    }

The index file already has r/w user permission...

![schermata 2017-07-21 alle 16 35 01](https://user-images.githubusercontent.com/20744688/28468231-9d6787b2-6e32-11e7-97f9-f86dd65361dd.png)

What can it be???

Thanks.

**Comment by giacomodeglinnocenti** [comment]
I have moved out the index file (storage/xxx.index) and made the insert again and it has happened immediatly.

 I've used tntsearch:import to speed up the indexing (elapsed ~1h 30m), I would like to try with the scout:import but it's too damn slow on 3M records (I think about 24 hours).
In fact the data are so much that I need to run the php artisan command without the memory_limit option.
`php -d memory_limit=-1 artisan tntsearch:import App\\MyModel`
I'm actually using my MacBook Air 8GB ram.
I would like to know how to speed up the scout:import, can I rent a big CPU/RAM server for a couple of hours somewhere and run scout:import on that?


I will try now to rerun the import with scout:import and let you know if things will goes better with a new index.

Otherwise is not acceptable to wait 30s for an insertion.
Is this a known issue, or system limitation or it is not supposed to be like this?

Any help will be appreciated, thanks.

**Comment by giacomodeglinnocenti** [comment]
Hi, 
 I've recreated the index and I can confirm this issue.

First of all, I would like to underline that a little help would be a great help and save me a lot of time.

This seems to me a major issue, as the TNTSearch is proposed as a good way to index and have a full-text search engine, this is really untrue as TNT SEARCH NOT WORK ON MILLIONS OF ROW.

My index entity consist in just ten field of string (from 5 to 50 chars length).

I hope I'm doing something wrong, because if this is the real situation I have lost a lot of time and this could be easily prevent by adding a note which specify this limit of TNTSearch on the README or this github home page.

Please help, thanks.

**Comment by giacomodeglinnocenti** [comment]
Just a last minute thought, but should a queue solve the issue? 

I'll try right now and let you know.

**Comment by nticaric** [comment]
Would you mind sharing your dataset with us so we can test it and if there are issues fix it? If the data is not private you can send it to tntstudiohr@gmail.com

**Comment by nticaric** [comment]
The index file is a regular sqlite file with only few tables in it, so in theory the insert operation shouldn't take to long

**Comment by giacomodeglinnocenti** [comment]
Hi,
 I put in place a queue and now it's a little bit better as the front-end obviously responds immediately.

The queue job is then executed in ~1m 10s, but some times it's still going in time-out and my queue worker getting killed. If then I rerun the queue worker it succeed on the second time. Anyway I will put a supervisor on place as suggested on L official docs. By the way, this last part is not a TNTSeach Scout Driver related issue and I will try to solve it by myself.

![schermata 2017-07-31 alle 12 31 29](https://user-images.githubusercontent.com/20744688/28774076-43f289a4-75ec-11e7-8a8a-cef7d50077dc.png)


Of course, would have been nice to know this from the beginning, a note on the Home Page would have sufficed.

FIY, it may be interesting for you to know that my dataset as the following structure:

CREATE TABLE `table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `field_1` varchar(255) DEFAULT NULL,
  `field_2` int(11) DEFAULT NULL,
  `field_3` varchar(255) DEFAULT NULL,
  `field_4` varchar(255) DEFAULT NULL,
  `field_5` varchar(7) DEFAULT NULL,
  `field_6` varchar(255) DEFAULT NULL,
  `field_7` varchar(255) DEFAULT NULL,
  `field_8` varchar(255) DEFAULT NULL,
  `field_9` varchar(31) DEFAULT NULL,
  `field_10` varchar(31) DEFAULT NULL,
  `field_11` varchar(127) DEFAULT NULL,
  `field_12` varchar(127) DEFAULT NULL,
  `field_13` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `braintree_id` varchar(255) DEFAULT NULL,
  `paypal_email` varchar(255) DEFAULT NULL,
  `card_brand` varchar(255) DEFAULT NULL,
  `card_last_four` varchar(255) DEFAULT NULL,
  `trial_ends_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3469855 DEFAULT CHARSET=latin1;

and this is my searchable conf:

```
    public function toSearchableArray()
    {
        $array = $this->toArray();
        $array = array_only($array, ['id','field_1','field_3','field_4','field_5','field_6','field_7','field_8','field_9','field_10']);
        return $array;
    }
```

There are 3 Millions rows. You can recreate the real dataset by just put random strings in it. I haven't the right to share the content around.

I still doesn't understand why it takes so long... May be that on the production server it will be faster, but anyway a minute for an insertion seems to me an huge time!

Let me know if you need any other info and if you can think of a solution!

Thanks,
 Giacomo

**Comment by nticaric** [comment]
Lets try to isolate only the insert and see how long it takes. Try this piece of code in a test route:

```php

use TeamTNT\TNTSearch\TNTSearch;


$config = [
    'driver'    => 'mysql',
    'storage'   => '/var/www/tntsearch/examples/'
];
$tnt = new TNTSearch;

$tnt->loadConfig($config);
$tnt->selectIndex("name.index");

$index = $tnt->getIndex();

//to insert a new document to the index
$index->insert(['id' => 'yourID', 'field_1' => 'value', 'field_2' => 'value']);

**Comment by roballport** [comment]
Whilst it doesn't help here immediately, I'm using TNT Search without Scout on ~1.6 million records (with 5 columns i.e. the ```toSearrchableArray()``` value). Indexing is performed in ~4 mins.

**Comment by giacomodeglinnocenti** [comment]
Well, thanks for the feedback, at least I'm not alone.

I apologize for my absence, by the way I will try what @nticaric suggested as soon as I have time and let you know if I can isolate the problem.

Another thought that I have is... while doing tntsearch:import doesn't the insertion time have to lengthen as the index grows up? Instead this doesn't seems to happen, so the mystery deepens...!
