### ISSUE TITLE
Search for all words

### ISSUE THREAD

**Issue by csb346** [teamtnt/laravel-scout-tntsearch-driver#111]
Performing a multiple word search, is it possible to retrieve models that have all terms indexed and not all models that have at least one os them indexed.

Example:
1-
Title: Table vintage
Body: beautiful furniture

2-
Title: modern table
Body: modern design

3-
Title: beautiful chair
Body: vintage design

Searching for "beautiful table" it returns all the items. How to get only the first one that has both words.
Is that possible with fulltext search?

Thanks for the help and Grat job! :)

**Comment by nticaric** [comment]
Yes it's possible. It's called boolean search. It can be set in the configuration file 
`config/scout.php`

**Comment by pedzed** [comment]
@nticaric But when you enable boolean search, special characters don't work. #133 

I would like to have all search terms included in the result set, but whilst allowing for special characters to be in the search query. How can that be achieved?
