### ISSUE TITLE
Breaking Change from #103 Option to use searchBoolean

### ISSUE THREAD

**Issue by tehwave** [teamtnt/laravel-scout-tntsearch-driver#112]
Hi,

An ErrorException is thrown with the msg `Undefined index: searchBoolean` because the`config/scout` file doesn't have the following line introduced in the #103 pull request.

```
'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
```

The fix from a user standpoint would be to just include the line, but I rather not spend time fixing bugs from breaking changes introduced in patches, provided the package follows semver, which I'd encourage you to do very much.

-- Cheers

**Comment by nticaric** [comment]
I totally agree with you. We try to follow semver as much as possible, but it seems that this change somehow slipped through
