### ISSUE TITLE
Indexing data

### ISSUE THREAD

**Issue by Pederytter** [teamtnt/laravel-scout-tntsearch-driver#113]
Hi there,

I have had quite some trouble with indexing the data correctly. I have tried a couple of ways, but nothing really seem to change the outcome. What I'm trying to get is only indexing the id and name of my model, but when I try and search for the model I get all the data from that models row.

Here is my Task model:

`<?php

namespace App;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use Searchable;

    public $asYouType = true;

    protected $guarded = [];

    public function toSearchableArray()
    {
        return [
            'id' => $this->id, // required
            'name' => $this->name,
        ];
    }
}`

After this I run .. scout:import App\\Task and output the search result like this:

`<?php

namespace App\Http\Controllers;

use App\Task;

class SearchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index($data)
    {
        //$results = Model::where('column', 'LIKE', '%value%')->get();
        $results = Task::Search($data)->get();
        return $results;
    }
}`

Not sure what I'm doing wrong here?

**Comment by stokic** [comment]
You tell the index on what to index on, ie. you can think of it as telling index: "ok here are the fields you can do a full text search on" but indexing has nothing to do with what you retrieve by searching meaning you search by some field, but you get the whole model as a result, that's the purpose of it :)

To put simply: you search by field name and it finds you the model which has this name that's it. Afterwards it's up to you what you want to with the model data.

Hope this makes it clearer, you can also check Scout documentation if you haven't already

**Comment by Pederytter** [comment]
Ahh I see, that makes perfect sense. Thanks for explaining it to me :)

However in that case how do I specify what it should retrieve from the database? The select() option isn't working for this case.

**Comment by nticaric** [comment]
In your case the `$results` variable is a collection. I you need just one column from it you could do 
`$results->pluck('name');`. For other cases you'll have to map through the collection and only choose the fields you need.

```php
$filtered = $results->map(function($item) {
   return [
      'name' => $item['name'], 
      'id' => $item['id']
]});
return $filtered;
```
