### ISSUE TITLE
Stemmer config

### ISSUE THREAD

**Issue by mrTimofey** [teamtnt/laravel-scout-tntsearch-driver#117]
May be I have missed something but I didn't see any way to change default stemmer.
Moreover I have tried to do it myself with TNTIndexerer::setStemmer/Language but these functions just insert other row to the `info` table instead of replacing old value with `UPDATE` so it just don't make sense.

Is there something I'm doing wrong or it can be an issue?

**Comment by nticaric** [comment]
The levenshtein distance is calculated between stems of the two words, that's why the distance is 2.

This article explains this https://www.elastic.co/blog/found-fuzzy-search

You could create an index without a stemmer and the above effect would be gone

**Comment by nticaric** [comment]
With the latest version of the driver its possible to set the stemmer via config.
ie.
```php
    'tntsearch' => [
        'storage'   => storage_path(), //place where the index files will be stored
        'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
        'fuzzy'     => [
            'prefix_length'  => 2,
            'max_expansions' => 50,
            'distance'       => 2
        ],
        'asYouType' => false,
        'stemmer'   => \TeamTNT\TNTSearch\Stemmer\NoStemmer::class
    ]
```
