### ISSUE TITLE
SearchableAs is equal to table

### ISSUE THREAD

**Issue by stevenklar** [teamtnt/laravel-scout-tntsearch-driver#12]
Hello,

as a multi database user - i need to define the exact name of index.
I have to tables with name 'users' and three models. "User", "FrontendUser", "BackendUser".
FrontendUser and BackendUser extends User and look for users on different database connections.

The table name is always "users".

Index of "users_index" will be created. And there is the problem.
As of now there is no possibility to make something like frontend_users_index, right?

Can you make a alternative model variable which can define the index name?

**Comment by stevenklar** [comment]
See #13

**Comment by nticaric** [comment]
You should be able to override the `searchableAs` method in each of your models, so it would look like this:

```php

class FrontendUser extends User
{
    use Searchable;

    public function searchableAs()
    {
        return 'frontend_users_index';
    }
}

**Comment by stevenklar** [comment]
If i do this, your engine try to access the database table "frontend_users" but thats wrong and that is exactly my problem.

**Comment by nticaric** [comment]
Oh, I see now your problem. This commit should fix it 

https://github.com/teamtnt/laravel-scout-tntsearch-driver/commit/03a9ab31aa96b83acb9ac888a48231dd0b01255d

Thanks for spotting this

**Comment by stevenklar** [comment]
Works. Thanks!
