### ISSUE TITLE
[question] Model::search($query)->get(); only returns 1 result.

### ISSUE THREAD

**Issue by bhulsman** [teamtnt/laravel-scout-tntsearch-driver#121]
Consider the following dataset:

- record 1; loremipsum
- record 2; loremdolor

Is there any way that searching for 'lorem' would only return record 2? 

Options `asYouType` and `fuzziness` are both `true`.

**Comment by stokic** [comment]
If that's your real dataset then it's not the best way of testing full text search I'm afraid. Full text search, unlike sql %like%, relies on other things like stemming words so could you please test with  real data and use appropriate Stemmer while indexing. 

If you have real data and this was just an example could you post a real example and we'll take it from there :)

**Comment by bhulsman** [comment]
It wasn't a real dataset, but I did just add the records like that. It's company names I'm working with here, so I can't post any. As I said I just added 'loremipum' and 'loremdolor' as company names and results are the same.

First of all, I'm using the Laravel Scout TNTSearch driver; so I'm not doing anything with the data before other than indexing it.

Can you maybe point me to the docs about 'stemmer', maybe I can find something there. The docs for laravel-scout-tntsearch-driver don't mention anything about it.

Thanks for replying so quickly! ^^

**Comment by stokic** [comment]
It's better if you have a real dataset but I'm not sure, are you having the same problem with real company names? If you can't post them could you use some public names like Google, Facebook etc... and see if that works of for you.

You can ignore Stemming comment for now ;)

**Comment by bhulsman** [comment]
I think the problem here is that it's just returning one result. No matter what I do, I never get more then one result.

```$companies = Company::search(request('query'))->get();```

Nothing fancy here, just following the plain simple example from the docs to get started. Any clue to why I'm only getting one result back, while there are more records matching the query?

**Comment by nticaric** [comment]
Try with this config:

```
'tntsearch' => [
    'fuzziness' => env('TNTSEARCH_FUZZINESS', true),
    'fuzzy' => [
        'prefix_length' => 2,
        'max_expansions' => 50,
        'distance' => 10
    ],
    'asYouType' => false,
],

**Comment by bhulsman** [comment]
Increasing the levenshtein distance does not seem to help, I tried reïmporting using `artisan scout:import` and `artisan tntsearch:import`, but no difference.

**Comment by nticaric** [comment]
Can you confirm that the àsYouType`option is set to false and fuzzines to true?

**Comment by bhulsman** [comment]
Using config below.

```
'tntsearch' => [
        'storage'  => storage_path('indexes'), //place where the index files will be stored
        'fuzziness' => env('TNTSEARCH_FUZZINESS', true),
        'fuzzy' => [
            'prefix_length' => 3,
            'max_expansions' => 50,
            'distance' => 10
        ],
        'asYouType' => false,
        'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
    ],
```

**Comment by bhulsman** [comment]
Found something... with examples 'loremipsum' and 'loremdolor' in place; searching for 'lorem' yields just one result, but searching for 'lorem ip' shows both.

**Comment by nticaric** [comment]
The index is a regular sqlite database, can you open it an dump the wordlist table here so we can take a look. It would be interesting to know if you have spaces in lorem ipsum because its very different to have "lorem ipsum" and "loremipsum"

**Comment by bhulsman** [comment]
See below, had to redact some names;

```
"29"	"1"	"1"	"1"
"30"	"[redacted]"	"1"	"1"
"31"	"2"	"1"	"1"
"32"	"[redacted]"	"1"	"1"
"33"	"3"	"1"	"1"
"34"	"[redacted]"	"1"	"1"
"35"	"4"	"1"	"1"
"36"	"loremipsum"	"1"	"1"
"37"	"5"	"1"	"1"
"38"	"loremdolor"	"1"	"1"
"39"	"6"	"1"	"1"
"40"	"facebook"	"1"	"1"
"41"	"7"	"1"	"1"
"42"	"googl"	"1"	"1"
"43"	"8"	"1"	"1"
"44"	"brain"	"1"	"1"
"45"	"pick"	"1"	"1"
```

**Comment by nticaric** [comment]
Can you first try to claer the config cache so we're sure that the config is correct before we go on

`php artisan config:clear`

**Comment by bhulsman** [comment]
Sorry, no difference; 'lorem' one result, 'lorem ip' two results.

**Comment by nticaric** [comment]
Just recreated your sample and I'm getting two results as expected. Can you try to delete the index from disk and then reimporting it. Also make sure that TNTSEARCH_FUZZINESS is set to true in your .env file.

**Comment by bhulsman** [comment]
Updated config (see below), deleted the index, imported the model, still strange results; searching for 'lore' returns one result, searching for 'lorr' returns two results. So making a typo works, oddly.

**Comment by nticaric** [comment]
Hmm something strange is going on, for your usecase I guess the n-gram approach would be the best. Here's a tutorial on how to do this http://tnt.studio/blog/did-you-mean-functionality-with-laravel-scout

**Comment by bhulsman** [comment]
I'll have a look on how to implement that. For now I'll fall back to Algolia again, but I'd rather not send any data to a search provider like that. Having something like TNTSearch locally is the prefered solution.

Thanks for your help and timely responses! ^^
