### ISSUE TITLE
Facade removed. Correct way to index models in Laravel with v1.0.7? 

### ISSUE THREAD

**Issue by marleybobby** [teamtnt/laravel-scout-tntsearch-driver#122]
I followed this tutorial http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5 but it seems that there isn't any facade provided, so how can I translate this 

```php
public static function insertToIndex($model)
    {
        TNTSearch::selectIndex('mymodel.index');
        $index = TNTSearch::getIndex();
        $index->insert($model->toArray());
    }
```

to a working piece of code?

Is my approach correct, or is there a better one?
```php
$tnt = new TNTSearch;
        $tnt->selectIndex('mymodel.index');
        $index = $tnt->getIndex();
        $index->insert($model->toArray());
```

~~And why isn't there a facade like in that tutorial described?~~
It seems that the Facade was removed with version 1.0.0. So what the correct way to call the Indexer in Laravel?

**Comment by stokic** [comment]
Did you add. a facade like tutorial suggests? And is. the facade included
in the autoload file? If not then you skipped a step, perhaps artisan
optmize?

**Comment by marleybobby** [comment]
I tried to add `'TNTSearch' => TeamTNT\TNTSearch\Facades\TNTSearch::class,` but there isn't a directory called Facade in that folder. So I'm not able to include sth. what isn't available.

**Comment by nticaric** [comment]
The facade has been removed when laravel introduced scout and isn't necessary anymore. I guess we should update the tutorial

**Comment by marleybobby** [comment]
Just figured out the same. There isn't any need to manually handle it, scout will do it for you. 

An update or a notice would be great.

**Comment by nticaric** [comment]
@marleybobby we just updated the tutorial, please try to follow it again and let us know if we skipped any steps.

http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5

**Comment by marleybobby** [comment]
Seems good to me. Found out the same approach.
