### ISSUE TITLE
Importer tries to select nonexistent columns, ignores toSearchableArray() values

### ISSUE THREAD

**Issue by judahnator** [teamtnt/laravel-scout-tntsearch-driver#125]
I am trying to have the `tntsearch:import` command index a model. I would like to index my models attributes, as well as its relationship with my `Users` model.

I setup my models `toSearchableArray()` function like this:
```php
public function toSearchableArray()
{
    return array_merge(
        $this->toArray(),
        [
            'owner' => $this->owner->full_name
        ]
    );
}
```

When I run the importer I get an error that looks like this:
```
[2017-11-29 15:53:32] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'owner' in 'field list'
```

I tracked down the problem to the ImportCommand file. It is grabbing the keys of the `toSearchableArray()` function and using that as the columns to select from the database.
https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/f7b97a66f1ebb6e86be8b02d6caa48917a8a00a7/src/Console/ImportCommand.php#L46-L54
This seems to be the root of the problem. It seems to be completely ignoring the results of the array, and instead just assuming the only items in the array will be model attributes.

Is there a workaround or a fix for this?

**Comment by nticaric** [comment]
I guess a workaround for creating the index would be to use the TNTSearch package directly and creating a laravel command. There you could write a join command to get the owner
