### ISSUE TITLE
Problem version

### ISSUE THREAD

**Issue by ferampe** [teamtnt/laravel-scout-tntsearch-driver#126]
Hello, I have a problem when I install laravel-scout-tntsearch-driver, I installed the teamtnt/tntsearch with v1.1.0 and laravel-scout-tntsearch-driver require the version v1.0.*

is it posible find a solution for this problem?

Thank you

![version tntsearch](https://user-images.githubusercontent.com/1254648/33466263-af9a14c2-d61a-11e7-962e-57b2fa63af86.jpg)

![conflict-driver](https://user-images.githubusercontent.com/1254648/33466284-e0e279fc-d61a-11e7-8e23-fe19e54b3b73.jpg)

**Comment by ferampe** [comment]
I fix the problem, I created a Fork and change version "teamtnt/tntsearch": "1.1.*", and from my composer fetch this fork.

**Comment by nticaric** [comment]
Glad you solved your issue!
