### ISSUE TITLE
Change results order by newest

### ISSUE THREAD

**Issue by pgrab86** [teamtnt/laravel-scout-tntsearch-driver#132]
I have seen this issue https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/59
It was a year ago. How about now? Is there any possibility, to order results by "newest" and have working pagination?

**Comment by nticaric** [comment]
The driver will return a laravel collection which can easily be sorted by date.

**Comment by pgrab86** [comment]
Yes, but for example if we have 700-800 results and I want to paginate it this way https://gist.github.com/vluzrmos/3ce756322702331fdf2bf414fea27bcb will it be "optimal"? I am just worried about search time and database queries

**Comment by jonbonsilver** [comment]
OK, I have seen this question asked a lot about this scout driver and I want to have an input Because I don't think it's @nticaric responsibility to help you with these kind of problems (and the fact that there are no other answers online. For anyone who wants a working relevancy and search function, you can have a look at my function.

Laravel relevancy or user defined sort function:

        $request = app()->make('request');
        $type = '';
        //not needed $search = trim(preg_replace('/\s+/', ' ',$request->search));

        if($request->has('search')) {
            $result = $this->search($request->search)->get()->load('genre')->load('director_obj');
  
            if($request->has('order') && $request->has('sort')) {

            	if ($request->sort == 'desc') {
            		$result = $result->sortByDesc($request->order);
            	} else {
            		$result = $result->sortBy($request->order);
            	}
                $type = $request->order;
            }          
        } else {
        	$result = $this->all();
        }

        $currentPage = LengthAwarePaginator::resolveCurrentPage();
        $perPage = 10;
        $currentPageItems = $result->slice(($currentPage * $perPage) - $perPage, $perPage)->all();
        $paginatedItems= new LengthAwarePaginator($currentPageItems , count($result), $perPage);
        $paginatedItems->setPath($request->url());


        return ['query' => $paginatedItems, 'type' => $type];

**Comment by thoresuenert** [comment]
This should be supported now. Support for order by and where clauses ist merged.
