### ISSUE TITLE
How to customize Array?

### ISSUE THREAD

**Issue by xsmartweb** [teamtnt/laravel-scout-tntsearch-driver#134]
`
public function toSearchableArray()
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }
`

I have many fields in table. So I think that make speed down because of massive indexing. 

Can you advice me how to customize array ?

**Comment by stokic** [comment]
In the array you can kick out the fields you don't need for searching, you can just use unset() on the fields you don't want being indexed...

**Comment by xsmartweb** [comment]
Sorry, sadly , I'm not good at PHP . 
Can you give me code snippets ?

**Comment by stokic** [comment]
`unset($array['iDoNotWantThisFieldIndexed)`

http://php.net/manual/en/function.unset.php

This is a Laravel Scout and basic php question really, it has nothing to do with this particular search driver.

**Comment by d4rkr3pt0r** [comment]
Choose your desire columns like this:
```
    public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            // other cols
        ];
    }
```

**Comment by rabpeter** [comment]
Thanks @d4rkr3pt0r
