### ISSUE TITLE
php artisan tntsearch:import App\\... Errors

### ISSUE THREAD

**Issue by xsmartweb** [teamtnt/laravel-scout-tntsearch-driver#135]
I used this command 
`
php artisan tntsearch:import App\\Models\CustomModel
`
In PDOStatement.php line 122

Empty row packet body

Is there any way to solve this ?

**Comment by stokic** [comment]
What steps have you already taken to try and fix this error? Did you google the error message, have you tried implementing suggestions from StackOverflow etc...? Here is one to get you started:

https://stackoverflow.com/questions/37092140/empty-row-packet-body-mysql

**Comment by xsmartweb** [comment]
Thanks @stokic 

Solved this issue myself.
