### ISSUE TITLE
Search results object type error

### ISSUE THREAD

**Issue by xsmartweb** [teamtnt/laravel-scout-tntsearch-driver#137]
Mostly search results is array object, 
but sometimes search results is json object like this {'7': {'id': '9989', 'first_name': 'Blabla'}...., '8': {....}}

But I want to get array results at all time.

Is there any solution for this ?

**Comment by stokic** [comment]
Show your code please.

Also, check Scout documentation https://laravel.com/docs/5.5/scout#searching

**Comment by xsmartweb** [comment]
I checked that laravel scout  doc already .
`
$providers = Provider::search($query)->where('type', 2)->get();
`

Some times results is array like this 
[{'id': '89999', 'first_name': 'adf', ....},
{....},..... 
]

But sometimes wrong results like this 
{'7': {'id': '9989', 'first_name': 'Blabla'}...., '8': {....}}

**Comment by nticaric** [comment]
This is not a TNTSearch issue but a laravel one. In case there is only one item it will return a json `object` and if there are multiple results it returns an `array`. You can cast the object to an array to cover this single results case
