### ISSUE TITLE
In TNTSearchScoutServiceProvider.php line 22: Unsupported operand types

### ISSUE THREAD

**Issue by digitlimit** [teamtnt/laravel-scout-tntsearch-driver#138]
I got error message below when I run `php artisan scout:import "App\Model"

In TNTSearchScoutServiceProvider.php line 22: Unsupported operand types

And here is line 22
`$config = config('scout.tntsearch') + config("database.connections.{$driver}");`

Why are you guys using `+`?

**Comment by digitlimit** [comment]
Ok I forgot to add, also + operand is for array_merge

```
'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
    'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
    'fuzzy' => [
        'prefix_length' => 2,
        'max_expansions' => 50,
        'distance' => 2
    ],
    'asYouType' => false,
    'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
],
```

**Comment by mnoquiao** [comment]
hi I am having the same issue right now can anyone tell me how did you fixed it?

**Comment by bill-dou** [comment]
Please run:

```php artisan config:cache```
