### ISSUE TITLE
Cannot search some data

### ISSUE THREAD

**Issue by xsmartweb** [teamtnt/laravel-scout-tntsearch-driver#139]
When I use this keyword (e.g., "JEN"), I can get correct result("JEN CHAO").

But when I entered whole keyword like this ("JEN CHAO"), and then tntsearch is not available to search that, it returns similar data like "JEN JEN Luis", etc...

Is there any solution for this?

**Comment by belzaaron** [comment]
+1 for this; it's not a huge issue at all, as I still get the search query result at the top. However, it'd be helpful if someone has a solution because it does apply unnecessary stress to the server to search for the rest of the similar entries when an exact has been searched for.

**Comment by stokic** [comment]
Yes exactly, you should set searchBoolean if you want that kind of behaviour

**Comment by michaelklopf** [comment]
@belzaaron hey, where did you find more information about `searchBoolean`?

**Comment by xsmartweb** [comment]
Hi @belzaaron , what is searchBoolean? 
What is function of that ?

**Comment by michaelklopf** [comment]
It‘s part of the config

```
'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
    'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
    'fuzzy' => [
        'prefix_length' => 2,
        'max_expansions' => 50,
        'distance' => 2
    ],
    'asYouType' => false,
    'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
],
```

**Comment by xsmartweb** [comment]
@michaelklopf , but why is it needed? what does that do ?

**Comment by stokic** [comment]
https://github.com/teamtnt/tntsearch#boolean-search
