### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by powolnymarcel** [teamtnt/laravel-scout-tntsearch-driver#140]
Hello,

I would like to search for the entire string, not for different words in a string:

Example : When I search for  =>  "the little red car"
the search will execute and search in each model for "the" + "little" + "red" + car +

I would like to search each model and only find articles that match exactky 

I would like to search each model and only find articles that match exactky  "the little red car".

Is it possible ?

**Comment by stokic** [comment]
Yes, see https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/139. In short, enable boolean search in config

**Comment by dily86** [comment]
Just copy paste this code in config/scout.php

    'tntsearch' => [
        'storage'  => storage_path(),
        **'searchBoolean' =>true**
    ],
