### ISSUE TITLE
PHP 7.2 compatibility issues

### ISSUE THREAD

**Issue by Harti** [teamtnt/laravel-scout-tntsearch-driver#145]
https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/a58861c7b549a96d629051129867966cc68752ec/src/Engines/TNTSearchEngine.php#L183

This is still triggering the `count(): Parameter must be an array or an object that implements Countable` ErrorException (probably because this can be null).

**Comment by nticaric** [comment]
Would `if (!$results['ids'] || count($results['ids']) === 0) {` help?

**Comment by Harti** [comment]
Thanks for the super swift reply! 
It appears so. I simply edited the code into the dependency (just to check!), and the Exception is gone.

**Comment by paschaldev** [comment]
@nticaric Suggestion. Instead of doing that, why not use type casting and cast the count result to an integer

```php
(int) count($results['ids'])

//If the value is null, the type casting will return 0
(int) null // => 0
```

**Comment by Harti** [comment]
@paschaldev umm, that doesn’t change that `count()`’s *argument* can be null, this triggering the PHP 7.2 warning requiring the argument to implement `Countable`, which `null` is not.

**Comment by paschaldev** [comment]
@Harti Oh yeah thats true. Just tried it with 7..2 and got the warning message

**Comment by DeehSlash** [comment]
Still getting this error

**Comment by jameswagoner** [comment]
Anyone do a pull request? This still seems to be an issue
