### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by TheSachin** [teamtnt/laravel-scout-tntsearch-driver#146]
Hi, guys when will be the version supporting Laravel 5.6 be released?

**Comment by nticaric** [comment]
Hmm, it should work with Laravel 5.6. What error are you getting?

**Comment by TheSachin** [comment]
No I have not tested it. Given on readme.md that it says that it supports Laravel 5.3/5.4. Hence i was bit curious.

**Comment by nticaric** [comment]
Well, test it and let us know if it works and we'll update the readme :D

**Comment by phyo1** [comment]
Hi all,
I would like to make key word search from the whole database in my website. Is it possible with TNTSearch Laravel? How to use multi-index searches in TNTSearch? Please kindly give me advice. Thanks.
