### ISSUE TITLE
Max index file size

### ISSUE THREAD

**Issue by phyo1** [teamtnt/laravel-scout-tntsearch-driver#149]
Hi all,

I'm start using TNTSearch for my web app. In my project, I must include keyword search from the whole database. I would like to know maximum index file size limitation and difference between TNTsearch driver and mysql driver with laravel scout. Please kindly help me, thanks.

**Comment by nticaric** [comment]
The theoretical limit of the index is 1.4e+14 bytes (140 terabytes, or 128 tebibytes, or 140,000 gigabytes or 128,000 gibibytes). Maximum number of rows in a index table is 18446744073709551616 or about 1.8e+19. Hopefully this is enough for your needs :)

The difference is that TNTSearch is much better :)

**Comment by phyo1** [comment]
Wow, Good! Many thanks for your details info. 👍
