### ISSUE TITLE
very low import model . 

### ISSUE THREAD

**Issue by GeoIntranet** [teamtnt/laravel-scout-tntsearch-driver#15]
Hi ! i'm trying to import différent model , who have différent size , i think the import is very very low ..... more than one hour , for a table with 30k record.
it's normal ? 

i have a intel core i7 with ssd and 16GO memory . it's note a hardware issue.

What do you think ?

**Comment by nticaric** [comment]
To drastically speed up the import we created a command

`php artisan tntsearch:import App\\Post`

Please try to update the package to the latest version and run the above code, with your model. 
If you don't mind sharing how long it takes for you to index the model with the new command

**Comment by GeoIntranet** [comment]
He throw me an exeception : 
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'App\\Incident' not found

package version 1.1.0

**Comment by nticaric** [comment]
The Model `App\Incident` must of course exist and be properly namespaced.

**Comment by GeoIntranet** [comment]
Of course it is , when i trigger the command 
php artisan tntsearch:import App\Incident - it's Very low 
and with the command 
php artisan tntsearch:import App\\Post
he trhow me [Symfony\Component\Debug\Exception\FatalErrorException]
Class 'App\Incident' not found 
>< don't understand Why

**Comment by nticaric** [comment]
if the command `php artisan scout:import App\\Incident` works, the command `php artisan tntsearch:import App\\Incident` should work also. The one for which you claim is "Very low" should fail, because you're missing a backslash. In order to help you, some more debug details would be necessary

**Comment by GeoIntranet** [comment]
i'm one window 10 
evironement : xampp php 5.6.23
hmm Laravel 5.3 
this is a fresh clean install 
first step laravel new scoutdemo
with composer i have import scout `composer require laravel/scout`
next add `Laravel\Scout\ScoutServiceProvider::class,` to the provider
next pusblish the config `php artisan vendor:publish`
next import your library `composer require teamtnt/laravel-scout-tntsearch-driver`
i have modify in the composer.json the version for update the last 1.1.0
next add the provider `TeamTNT\Scout\TNTSearchScoutServiceProvider::class,`
next add the path storage 
generate model `php artisan make:model Incident`
use the trait searchable
and try both command : 
`php artisan tntsearch:import App\\Incident` = Doesn't work
`php artisan tntsearch:import App\\Incident` = Works but slowly 

if you need more detail , tell me  thanks for your advice

**Comment by nticaric** [comment]
Whats the difference between the one command that works and the one that doesn't?

**Comment by GeoIntranet** [comment]
the slash , the first has two slah , and the second one slash , command with one slash work slow, the other , doesn't work

**Comment by nticaric** [comment]
Ok, the command that works how long does it take? And how many records do you have?

**Comment by GeoIntranet** [comment]
soooooo long , yesterday , i have executed the command , for 3k record , it take more than two hour .

the entire table have 30 - 40 k record . i have canceled the process befor end

**Comment by nticaric** [comment]
Yesterday you used `scout:import` today it's `tntsearch:import`. Can you show us the table shema? Indexing time and date fileds could slow down't the process, so those fields should be excluded. Also, blob fields, slow it down, drastically.
 Whats the language of the content in this table?

**Comment by GeoIntranet** [comment]
of course i could show you 
--

Target Server Type    : MYSQL
Target Server Version : 50155
File Encoding         : 65001

Date: 2016-08-26 13:40:48
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for incidents
-- ----------------------------
DROP TABLE IF EXISTS `incidents`;
CREATE TABLE `incidents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(6) NOT NULL DEFAULT '0',
  `INCIDENTS_nsoc` varchar(30) DEFAULT NULL,
  `INCIDENTS_tel` varchar(20) DEFAULT NULL,
  `INCIDENTS_adr1` varchar(30) DEFAULT NULL,
  `INCIDENTS_adr2` varchar(30) DEFAULT NULL,
  `INCIDENTS_cp` varchar(5) DEFAULT NULL,
  `INCIDENTS_ville` varchar(25) DEFAULT NULL,
  `INCIDENTS_contact` varchar(25) NOT NULL DEFAULT '',
  `commande_id` varchar(7) NOT NULL DEFAULT '',
  `INCIDENTS_serial` varchar(30) NOT NULL DEFAULT '',
  `INCIDENTS_open` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `INCIDENTS_lastact` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `INCIDENTS_nextact` datetime DEFAULT NULL,
  `INCIDENTS_level` tinyint(1) NOT NULL DEFAULT '0',
  `INCIDENTS_etat` tinyint(1) NOT NULL DEFAULT '0',
  `use_id` tinyint(1) NOT NULL DEFAULT '0',
  `INCIDENTS_garant` tinyint(1) NOT NULL DEFAULT '0',
  `INCIDENTS_titre` varchar(200) NOT NULL DEFAULT '',
  `INCIDENTS_explic` longtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_client` (`client_id`),
  KEY `id_cmd` (`commande_id`),
  KEY `open` (`INCIDENTS_open`),
  KEY `lastact` (`INCIDENTS_lastact`)
) TYPE=MyISAM AUTO_INCREMENT=31617 ROW_FORMAT=DYNAMIC;

**Comment by GeoIntranet** [comment]
char set : latin1
collation : latin1_swedish_ci

maybe it could be impact the performance

**Comment by nticaric** [comment]
Ok, great. Let's try with this:

```php

class Incident extends Model
{
    use Searchable;

    //fields you want to make searchable
    public function toSearchableArray()
    {
        return [
            'INCIDENTS_nsoc' => $this->INCIDENTS_nsoc,
            'INCIDENTS_tel' => $this->INCIDENTS_tel,
            'INCIDENTS_adr1' => $this->INCIDENTS_adr1,
            'INCIDENTS_adr2' => $this->INCIDENTS_adr2,
            'INCIDENTS_contact' => $this->INCIDENTS_contact,
            'INCIDENTS_serial' => $this->INCIDENTS_serial,
            'INCIDENTS_titre' => $this->INCIDENTS_titre
        ];
    }
}
```

**Comment by GeoIntranet** [comment]
ok , i will try this , right now i can't test . i'm not on my dev computer 
thanks for your answer

**Comment by nticaric** [comment]
ok, let us know if excluding the non text fields helped

**Comment by GeoIntranet** [comment]
ok , i have test , and you'r write ! my INCIDENTS_explic champ , make import realy low , if i remove this champ , it's good ! 

thanks for your times !

**Comment by shailesh-matariya** [comment]
Not knowing from my side issue, But I have tried all those above, they didn't worked. 
finally I have tried like this: 
php artisan scout:import App\\Account
without quotes, It's works fine.
