### ISSUE TITLE
SQLSTATE[HY000]: General error: 5 database is locked

### ISSUE THREAD

**Issue by MadMikeyB** [teamtnt/laravel-scout-tntsearch-driver#151]
Hi there,

I'm getting the database being locked every day or so. I'm running quite a high traffic site with multiple indeces and they're seemingly auto-locking which is breaking functionality every day..

Any fix to this?

**Comment by nticaric** [comment]
Do you use multiple queue workers?

**Comment by MadMikeyB** [comment]
Nope, just the one.

**Comment by MadMikeyB** [comment]
@nticaric happy to share error logs with you - this happens constantly now.

**Comment by juehai** [comment]
@MadMikeyB please have a look this https://github.com/teamtnt/tntsearch#examples

I think you may give a try about changing the /config/scout.php config file, and passing the MySQL config to TNTSearch.

**Comment by MadMikeyB** [comment]
Thanks everyone, I did solve this issue by enabling the Scout Queue in my .env file. Dumb moment from me for sure!

```
SCOUT_QUEUE=true
```

**Comment by AdnanHussainTurki** [comment]
> SCOUT_QUEUE=true

Will make all MakeSearchable Jobs, you search results will be inaccurate unless you have queue worker running.
