### ISSUE TITLE
(Laravel 5.6 support) Add support for Scout's new `shouldBeSearchable` function

### ISSUE THREAD

**Issue by neumannjan** [teamtnt/laravel-scout-tntsearch-driver#153]
See here: [Conditionally Searchable Model Instances](https://laravel.com/docs/5.6/scout#conditionally-searchable-model-instances). `tntsearch:import` currently does not take `shouldBeSearchable` into consideration.

TntSearch probably also does not take the new ["configuring the model ID" functionality](https://laravel.com/docs/5.6/scout#configuring-the-model-id) into consideration, but I have not tested this.

**Comment by slakbal** [comment]
Would be great if we can get to the latest Laravel version also.
