### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by omenejoseph** [teamtnt/laravel-scout-tntsearch-driver#160]
I get this error when trying to install the package... Any advise please? Thanks

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - teamtnt/laravel-scout-tntsearch-driver v3.0.6 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.5 requires teamtnt/tntsearch 1.2.* -> satisfiable by teamtnt/tntsearch[v1.2.0].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.0 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.1 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.2 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.3 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.4 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/tntsearch v1.3.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.2.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.7 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - Installation request for teamtnt/laravel-scout-tntsearch-driver ^3.0 -> satisfiable by teamtnt/laravel-scout-tntsearch-driver[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by stokic** [comment]
Well it says that you are missing sqlite3 extension so install it and
everything will be ok :)

**Comment by bloggervista** [comment]
Yes enable sqlite3 driver because we need it for indexing etc.

**Comment by Ahmed-Aboud** [comment]
for xampp users remove ; before extension=sqlite3 and restart the server

**Comment by shirshak55** [comment]
ahh don't use teamtnt now as it don't work for 5.8 and it is too buggy.. Either use algolia or elastic search :)

**Comment by stokic** [comment]
Really? Show us a screenshot of "don't work" and "too buggy". Which one is it? It doesn't work or is it buggy? :)

**Comment by shirshak55** [comment]
@stokic please don't mind but yea it really has issue. 

Search
Indexing



Search is not accurate usually like sometime small difference also dont work. Elastic search works on every usual and normal case :)

Indexing really has problem . Like sometime it don't index properly and it usually has problem on many bulk updates 👍 


I think instead of maintaining it how about maintaining and thinking about
https://github.com/cviebrock/laravel-elasticsearch which is more future proof also :)

**Comment by stokic** [comment]
Sorry, you haven't shown one example of anything you wrote about. "Sometimes", without an example is not how you report a problem or make an argument. 

Also suggesting to ditch your own package (which has been downloaded ~ 270,000 times and used in many CMS systems like Grav CMS) and maintain another package is extremely impolite and rude.

If you are not using the package then please move on, there is no need to comment if you don't have any constructive criticism.

**Comment by pamekar** [comment]
Just in case someone comes across this.

I use tntsearch because of how easy and flexible it is. I know it doesn't support 5.8, but who cares? I had to downgrade my laravel app to 5.7 to use, while I hope for when there'll be support for 5.8, or 5.9.

In the meantime, I'm sticking to tntsearch. If I _really really_ need to upgrade my laravel version, and there's no support for it then, maybe I'll try some other package. 

PS: I really hope to see support soon :smile
