### ISSUE TITLE
Index specific columns

### ISSUE THREAD

**Issue by nasirkhan** [teamtnt/laravel-scout-tntsearch-driver#163]
I want to search on the `name` and `description` columns of my table. I configured my Model as following and assumed that only `name` and `description` fields will be returned as the result. But it is showing all the columns of the table, so is it the situation that all the columns have been indexed? 
also i am getting some results where there is no match at all

```
use Laravel\Scout\Searchable;

class Book extends Model
{
    use Searchable;

    protected $table = 'books';

    public function searchableAs()
    {
        return 'public_books_index';
    }

    public function toSearchableArray()
    {
        $array =  [
            'id'      => $this->id,
            'name'    => $this->name,
            'description' => $this->description
        ];

        return $array;
    }

...
```

**Comment by stokic** [comment]
Since index is just an sqlite file you can open it with your preferred database tool and see what exactly it indexed :)

Laravel Scout will return the whole model, this has nothing to do with tntsearch, but the search will be based on the fields which are indexed
