### ISSUE TITLE
[PR]: Fix pagination when where() is applied and add complex db queries as constraints to search

### ISSUE THREAD

**Issue by michaelklopf** [teamtnt/laravel-scout-tntsearch-driver#165]
Due to our requirements in searching through our data, we had problems with filtering and querying the results of the `search()` function. Furthermore we noticed a deviation in the number of returned objects from the search and the pagination.

This behavior was already mentioned in these issues:
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/142
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/100

We think the problem started here, with the change that introduced where() clauses:
https://github.com/teamtnt/laravel-scout-tntsearch-driver/commit/7ff5de8bab2c157de1ad68cd9f131eddc0a8338b
The changes did not take the pagination into account.

This is a problem because the tnt search engine calls the driver functions in a specific order: 
https://github.com/laravel/scout/blob/f1b5d65a7d4a70bafaba7ec996176e95341c44ec/src/Builder.php#L220
The `paginate()` function returns the parameters for the pagination depending only on the results from the search. The `map()` function filters on the results after that, where the `where()` statements are applied. 

Problems:
- The current `where()` solution is called on the collection because tnt-search does not support `where()` clauses
- when filtering with `where()` the pagination is off because pagination is computed before the `where()` statements are applied

Solution:
- apply `where()` statement on database
- compare the search results with the results from the database query. Discard the elements from search results that are not part of the database query result. Compute pagination afterwards

Additional feature:
- Option to apply complex database queries as constraints in form of a new macro that will be used when querying the database and comparing the results with those from the search in the index

See the PR for our changes:
https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/166

**Comment by thoresuenert** [comment]
@nticaric thanks for merging our pr so quickly. 

Do you have plans for the next release? Do you close this issue with the next release?

**Comment by nticaric** [comment]
Thanks for the PR guys, a new version has just been released

**Comment by theara72** [comment]
hello ! it would be great if you could show some sample code to apply on your solution. im not quite understand your concept yet.
