### ISSUE TITLE
HOWTO: Programmatically enabling boolean search and vise versa...

### ISSUE THREAD

**Issue by imonoid** [teamtnt/laravel-scout-tntsearch-driver#169]
Hello,

Is there a way to switch to boolean search programmatically instead of chaning the setting inside scout.php? I am creating a search where the user can opt to choose basic search or the boolean search. How can we do this?

Thanks,
Ra

**Comment by thoresuenert** [comment]
@imonoid did you try to overwrite the values at runtime?
https://laravel.com/docs/5.6/configuration#accessing-configuration-values

**Comment by imonoid** [comment]
hi @thoresuenert,

thansk for the feedback.  I try to avoid doing that as it seems to change the particular config value for everyone.  For the moment, i am looking to use the non laravel tnt lib.  maybe this is the only solution for now.

**Comment by imonoid** [comment]
@thoresuenert this is the code:

    if (!empty($k)) {

          if (!empty($filter['with_boolean_search']) && $filter['with_boolean_search'] == 1) {

            config(['scout.tntsearch.searchBoolean' => true]);
            //$k = trim($this->booleanSearch2($k));

          } else {
            config(['scout.tntsearch.searchBoolean' => false]);
          }

          $withKeyword = true;
          $resumeIds = \App\Resume::search($k)->get()->pluck("id")->toArray();
    }

i have not thoroughly tested it, but seem to have worked.  right now, that feature has been removed in our website as my boss wanted a simplified search with no boolean search option anymore.
