### ISSUE TITLE
import model with specific condition

### ISSUE THREAD

**Issue by GeoIntranet** [teamtnt/laravel-scout-tntsearch-driver#17]
Hi ! me again ! 
i'd like to know if it's possible to index a model with a specific condition .
i have a model Stock , with many article in stock . 
an article can have a stat inStock , and a stat outStock .
i would like ton index only article instock ,is it possible ?

**Comment by RyanThompson** [comment]
You would want to conditionally exclude it from Laravel's observer:

```
if (!$instance->isSearchable()) {
    ModelObserver::disableSyncingFor(get_class(new static));
}
```

This is in a model's `boot` method.

**Comment by GeoIntranet** [comment]
but where is the condition  ? 

Cause if i type tntsearch:import App\myTable

itwill import ALL the table , and , i want import Only specific record of the table , in my case i want to import only record in my table with a stat inStock

**Comment by nticaric** [comment]
You can create a custom command for creating an index and specify a condition there if needed like:

```php
use TNTSearch;

//indexing
$tnt = new TNTSearch;
$indexer = $tnt->createIndex('articles.index');
$indexer->query('SELECT id, article FROM articles WHERE published = 1;');
$indexer->run();
```

**Comment by GeoIntranet** [comment]
thank's for answer ! i will try ! :)
