### ISSUE TITLE
Geo Search possible?

### ISSUE THREAD

**Issue by ge022** [teamtnt/laravel-scout-tntsearch-driver#170]
Is TNTGeoSearch possible with this library? How can I implement this feature into my existing app that's using this driver?

**Comment by nticaric** [comment]
It possible but not with the scout driver, take a look here https://github.com/teamtnt/tntsearch

**Comment by ge022** [comment]
@nticaric I was looking at the tntsearch documentation, but I can not see how I can search using my existing created by this driver.

**Comment by nticaric** [comment]
You cannot use the existing index created with scout, you have to create a new one. In the readme is a basic example

https://github.com/teamtnt/tntsearch#geo-search

**Comment by ge022** [comment]
That is a deal breaker for me... I was really hoping I could geo search the existing index.
