### ISSUE TITLE
leftJoinSub() is not a method in Laravel<5.6

### ISSUE THREAD

**Issue by pdanny** [teamtnt/laravel-scout-tntsearch-driver#171]
Trying to apply pagination on a query with where clauses results in an error for L5.5 or older. `leftJoinSub()` is only a method in L5.6. 

`Call to undefined method Illuminate\Database\Query\Builder::leftJoinSub()`

**Comment by MehediDracula** [comment]
I'm also facing the same issue!

**Comment by MehediDracula** [comment]
I'm also facing the same issue on Laravel `5.5`. Looks like this is happening because of this commit https://github.com/teamtnt/laravel-scout-tntsearch-driver/commit/a900b0a80c44f256a12dccc75c81507a04ac42fa

I've downgraded to version `3.0.6` to fix this issue.

**Comment by hackjie** [comment]
@nticaric Laravel 5.5 face the same problem

```
 Topic::search($q)->paginate(15);
```

**Comment by thoresuenert** [comment]
We will take care of this.
We are working on a replacement for leftJoinSub introduced in L5.6

**Comment by thoresuenert** [comment]
Can anyone test this fix:

replace `leftJoinSub` https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L141 with:

```
->join('('.$sub->getQuery()->toSql().') as sub', $subQualifiedKeyName, '=', $qualifiedKeyName, 'left', false)
    ->addBinding($sub->getQuery()->getBindings(), 'join')
```

**Comment by michaelklopf** [comment]
Fix didn't work. Will work on it later this week.

**Comment by Mohammad-Alavi** [comment]
I am also running into this problem. any news of a fix soon?

**Comment by michaelklopf** [comment]
How about this:

Replace the `->leftJoinSub` line in 

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L141 

with

`
->leftJoin(DB::raw('(' . $sub->getQuery()->toSql() .') as sub'), $subQualifiedKeyName, '=', $qualifiedKeyName)
`

And on top add:
`
use Illuminate\Support\Facades\DB;
`

**Comment by luisdalmolin** [comment]
Getting the same error in a Laravel 5.5 app. I was able to fix by adding the missing methods as macros in my `AppServiceProvider`:

```php
use Closure;
use InvalidArgumentException;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

// needed because of the TNT search scout package uses methods that are specific from laravel 5.6
// may be able to remove this if this app gets upgraded OR they fix the issue: https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/171
QueryBuilder::macro('joinSub', function ($query, $as, $first, $operator = null, $second = null, $type = 'inner', $where = false) {
    list($query, $bindings) = $this->createSub($query);
    $expression = '('.$query.') as '.$this->grammar->wrap($as);
    $this->addBinding($bindings, 'join');
    return $this->join(new Expression($expression), $first, $operator, $second, $type, $where);
});

QueryBuilder::macro('leftJoinSub', function ($query, $as, $first, $operator = null, $second = null) {
    return $this->joinSub($query, $as, $first, $operator, $second, 'left');
});

QueryBuilder::macro('createSub', function ($query) {
    if ($query instanceof Closure) {
        $callback = $query;
        $callback($query = $this->forSubQuery());
    }
    return $this->parseSub($query);
});

QueryBuilder::macro('parseSub', function ($query) {
    if ($query instanceof self || $query instanceof EloquentBuilder) {
        return [$query->toSql(), $query->getBindings()];
    } elseif (is_string($query)) {
        return [$query, []];
    } else {
        throw new InvalidArgumentException;
    }
});
```

**Comment by IhwanID** [comment]
got this : BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::leftJoinSub()

when i user method $posts = Post::search($request->get('query'))->where('status' , 1)->orderBy('published_at', 'DESC')->paginate(4);

but working smoothly when just use $posts = Post::search($request->get('query'))->get();

i dunno why, help me. thank you

**Comment by michaelklopf** [comment]
See https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/189 for a possible fix.
