### ISSUE TITLE
Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map($results, $model) must be compatible with Laravel\Scout\Engines\Engine::map(Laravel\Scout\Builder $builder, $results, $model)

### ISSUE THREAD

**Issue by bradley-varol** [teamtnt/laravel-scout-tntsearch-driver#175]
`Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map($results, $model) must be compatible with Laravel\Scout\Engines\Engine::map(Laravel\Scout\Builder $builder, $results, $model)`

I am receiving this exception when calling `search()` on a model.

I have temporarily fixed this by changing the signature of the map function from
`public function map($results, $model)`
to
`public function map(Builder $builder, $results, $model)`

**Comment by bradley-varol** [comment]
Okay when creating a model I have used `search()` in I'm receiving:
```
ErrorException (E_NOTICE)  
Undefined index: id  
\vendor\teamtnt\tntsearch\src\Support\Collection.php:97
```

**Comment by jhm-ciberman** [comment]
Same for me. (New user here!) 
Will be this fixed soon? I have a deadline and I need to know if can I use this package. Thanks. 😄

**Comment by bradley-varol** [comment]
I really need a fix for this otherwise I'm going to have to switch to a different driver.

**Comment by jhm-ciberman** [comment]
Sorry, but are you sure you are using Scout 4.0.*?
Can you check the version in composer-lock.json? (Not in composer.json) 

Maybe you run composer install instead of composer update

**Comment by bradley-varol** [comment]
```
"name": "laravel/scout",
            "version": "v4.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/scout.git",
                "reference": "f1b5d65a7d4a70bafaba7ec996176e95341c44ec"
            },
```

**Comment by nticaric** [comment]
just published a new release with the fix https://github.com/teamtnt/laravel-scout-tntsearch-driver/releases/tag/v3.0.8

**Comment by bradley-varol** [comment]
I'm still receiving this error when saving or creating a searchable model and i've updated to `v3.0.8`. 😭

**Comment by ITwrx** [comment]
i ran composer update and it installed v3.0.8 but i still get the error. maybe there's something else i'm supposed to do?

**Comment by nticaric** [comment]
@bradley-varol it's a different error than the one in the title :) it tells us that you don't have the latest scout driver v5.0.2 is the latest

**Comment by nticaric** [comment]
just created another release v3.1.0 that will force laravel scout 5.0.*, so the error should be gone

**Comment by bradley-varol** [comment]
Oops, I forgot that I had downgraded my Scout version following jhm-ciberman's suggestion.
Okay, I'm now able to search 🎉 but when updating or creating a model I get
```
ErrorException (E_NOTICE)
Undefined index: id
\teamtnt\tntsearch\src\Support\Collection.php:97

```

`php artisan scout:import "App\Model"` is also failing with this exception.

**Comment by michaelklopf** [comment]
@bradley-varol 
This kind of error was mentioned here https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/56

**Comment by bradley-varol** [comment]
If you see my comment on that issue thread, you'll see that adding the primary key didn't work. I'm not sure what I'm doing wrong.

**Comment by hackjie** [comment]
@nticaric v3.1.0 will cause another problem

```
Call to undefined method Illuminate\Database\Query\Builder::leftJoinSub()
```

**Comment by michaelklopf** [comment]
See https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/171 for this issue

**Comment by D-sense** [comment]
> just created another release v3.1.0 that will force laravel scout 5.0.*, so the error should be gone

I had a similar issue. This fixed it for me. Thank you.
