### ISSUE TITLE
Fuzzy search in persian words (utf-8)

### ISSUE THREAD

**Issue by mahmod2000** [teamtnt/laravel-scout-tntsearch-driver#179]
Hi,
first of all, thanks a lot for this great package.

I need fuzzy search in Persian words and I couldn't find any solution about that.
Please give me a trick about that.
Thanks in advance.

**Comment by Yarandi** [comment]
Hi @mahmod2000 
I did test the fuzzy search and this worked good. 
You should override fuzziness value in TNTSearch object.

```
        $tnt = new TNTSearch;
        $tnt->fuzziness = true;
        $posts = Post::search($request->get('search'))->get();
```
If you search  "علوم" word , it will also return "علوی" if you have it in your indexed data.
I hope it help you
