### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by GeoIntranet** [teamtnt/laravel-scout-tntsearch-driver#18]
hi , 
If a table contain to many record ( 180k ) 
when i import this table , he stop on the memory limit : 
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2656 bytes)`
is there a solution ?

**Comment by nticaric** [comment]
This issue can be solved by creating a custom command that uses TNTSearch directly. If you manually create a connection to the database, TNTSearch will know how to deal with your memory
issue because it sets `PDO::MYSQL_ATTR_USE_BUFFERED_QUERY` which is the key to your problem.

Another solution is to use `php artisan scout:import Model`, but the issue there is that it might be slow

**Comment by GeoIntranet** [comment]
hmmm,  can you give me an example ? 
i never create any command .

**Comment by nticaric** [comment]
Here's how your command could look like:

```php
<?php
namespace App;

use TeamTNT\TNTSearch\TNTSearch;

class IndexLargeTable extends Command
{

    protected $signature = 'index:large-table';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Indexes Large Table using TNT Search';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $tnt = new TNTSearch;
        $tnt->loadConfig([
            'driver'    => 'mysql',
            'host'      => config('database.connections.mysql.host'),
            'database'  => config('database.connections.mysql.database'),
            'username'  => config('database.connections.mysql.username'),
            'password'  => config('database.connections.mysql.password'),
            'storage'   => storage_path()
        ]);
        $indexer = $tnt->createIndex('large.index');
        $indexer->query("SELECT id, title, text  FROM posts WHERE some=condition;");
        $indexer->run();
    }
}
```

After registering the command you would simply run `php artisan index:large-table`. Since the index storage location should be the same, scout will know how to query the index

**Comment by GeoIntranet** [comment]
thanks for help ! i will try this !

**Comment by GeoIntranet** [comment]
i get an error , cause in my table i don't have a id field , but a table_id field , and the command throw an exception : 
[ErrorException]
  Undefined index: id

**Comment by nticaric** [comment]
Try with 

```php

$indexer->setPrimaryKey('table_id');
$indexer->run();

```

**Comment by GeoIntranet** [comment]
thanks =)

**Comment by nticaric** [comment]
How long does it take to index 180k records? I'm interested in the numbers :)
