### ISSUE TITLE
Does not bring results after update a field Model

### ISSUE THREAD

**Issue by barbosa89** [teamtnt/laravel-scout-tntsearch-driver#180]
I have a User model:

#example
$user = new User();
$user->name = 'Tony';
$user->status = false;
$user->save();

After, I can search:

User::search('tony')->get();

I want to update the status field:

$user->status = true;
$user-save();

But after updating,  does not bring result. It seems that when updating a single field, the other fields are updated empty in the indexes.

**Comment by josegus** [comment]
same here. Not working with laravel 5.8 and last scout package
