### ISSUE TITLE
General error: 5 database is locked

### ISSUE THREAD

**Issue by elephantux** [teamtnt/laravel-scout-tntsearch-driver#182]
`General error: 5 database is locked in /var/www/mysteria.city/vendor/teamtnt/tntsearch/src/TNTSearch.php:411`

Queue works with database:
```
'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
        ],
```

On server work Supervisor with this settings:
```
[program:mcity-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/mysteria.city/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=root
numprocs=8
redirect_stderr=true
stdout_logfile= /var/www/mysteria.city/worker.log

```

Scout has default settings. Console command `php artisan tntsearch:import App\\Post` work fine without any errors.

Any ideas?

**Comment by nticaric** [comment]
Yeah, multiple processes are accessing the index at once. You should somehow restrict it to one worker for the indexing

**Comment by elephantux** [comment]
Ho to set second separate supervisor worker for indexing only? And restrict indexing in main worker? Any example may be?

**Comment by thoresuenert** [comment]
@elephantux https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/61#issuecomment-401409268

**Comment by vbasky** [comment]
Any updates to this issue, PhpUnit tests get locked up on any class using ` use Searchable` having `SCOUT_DRIVER=tntsearch` in scout.php set and any workarounds haven't proved fruitful so far
