### ISSUE TITLE
Filtering Results

### ISSUE THREAD

**Issue by RyanThompson** [teamtnt/laravel-scout-tntsearch-driver#19]
Am I correct to assume that using `where` filters through scout is not implemented yet? I see the engine's `filters` method but it's not being used at all.

If there's an alternate way about it I would love a pointer - thanks!

**Comment by nticaric** [comment]
Yes, you are correct. This is because TNTSearch in the current version is field agnostic, so it doesn't know the difference between two fields. It only cares if the search query is contained in a document, but it doesn't know if its in the title, content, comments etc.

**Comment by RyanThompson** [comment]
Where is this feature at in the roadmap? Any near-future plans to implement filters like this? I would see no reason to look elsewhere with 1.) Filters and 2.) Weight control / ordering (the latter being less important in my eyes).

Thoughts?

**Comment by nticaric** [comment]
Yeah, we plan to implement this, but I am not sure exactly when. The project currently does not
generate any income for us so we only dedicate our spare time to it. Research takes most of the time. The coding is only a tip of the iceberg.

**Comment by RyanThompson** [comment]
Care to share more about approaching this? Seems like since Boolean searches are already in place - it should be part way there in adding a filter like this.

If I can figure it out I'll submit a PR. PyroCMS is shipping out of the box using this engine for scout since its local storage.

Thoughts?

**Comment by stokic** [comment]
Thumbs up for using this driver in PyroCMS :)

**Comment by bradgenereux** [comment]
+1 Great package so far! Would love the ability for a simple where clause.

**Comment by fredlahde** [comment]
Are there any news about this?
