### ISSUE TITLE
Support for Queues?

### ISSUE THREAD

**Issue by reminisc3** [teamtnt/laravel-scout-tntsearch-driver#193]
Hi,

Just wondering if this package supports queues? I am using Laravel 5.7 with Redis and noticed that the index files fail to be generated whenever SCOUT_QUEUE=true. When I set to false and use scout:import or update a model with the Searchable trait, the index files are generated.

Thanks!

**Comment by thoresuenert** [comment]
be explicit about "fails to be generated"?

We are using it with queues in a production environment without a problem in combination with laravel/horizon

**Comment by reminisc3** [comment]
I am using Horizon as well to monitor the queue. I can see that the queue jobs are being processed successfully, however, I am not seeing any index files being created in the storage folder. I am not seeing any errors or exceptions either when creating/updating models either.

Am I correct in assuming that the index files are supposed to be generated automatically when creating or updating models with the Searchable trait?

Thanks

**Comment by reminisc3** [comment]
Hi,

After doing some more testing, here are my findings:

- Running `php artisan scout:import App\\User` results in no index file being generated
- Running `php artisan tntsearch:import App\\User` results in the index file being successfully generated
- Seeding a fresh app with 5 model inserts without running tntsearch:import beforehand results in the index file NOT being generated (I would expect the file to be generated on the fly)

I am not seeing any issues with the config, and here is an example of a successful queue worker where no index file was generated:

![image](https://user-images.githubusercontent.com/5093706/45591358-954fea00-b91e-11e8-9b23-2b50221e03a8.png)

I am ok with running tntsearch:import when bootstrapping my app for all my models beforehand - but not sure if this is expected behavior.

Some screenshots of my config:

//horizon.php
![image](https://user-images.githubusercontent.com/5093706/45591391-5d957200-b91f-11e8-8d96-7433a55dbff5.png)

//scout.php
![image](https://user-images.githubusercontent.com/5093706/45591394-6e45e800-b91f-11e8-9273-aab8ab70afbb.png)

![image](https://user-images.githubusercontent.com/5093706/45591397-887fc600-b91f-11e8-9d65-7792413e2330.png)

//queue.php
![image](https://user-images.githubusercontent.com/5093706/45591406-d268ac00-b91f-11e8-97ca-0f2074417d5f.png)


Thanks
