### ISSUE TITLE
Searching in different models in same request fails

### ISSUE THREAD

**Issue by leptoquark1** [teamtnt/laravel-scout-tntsearch-driver#197]
Since version 3.2.0 following will crash since the "$query" is not reset.

```
    $users = \App\User::search($query)->get();
    $blogs = \App\Blog::search($query)->get();
```

Presuppose is that the query give a result in each model.

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/e4050ca4ac2f1ca156c54a5b41de3fbd8f865875/src/Engines/TNTSearchEngine.php#L226-L228

**Comment by daniel3303** [comment]
@n0script please release a new version for this fix
