### ISSUE TITLE
filter word OR AND condition in the search method

### ISSUE THREAD

**Issue by GeoIntranet** [teamtnt/laravel-scout-tntsearch-driver#20]
if i need to search in index two specific WORD , 
`FooBar::search('Foo Bar')->get();`

the resulte show "Foo or/and Bar " but not only "Foo AND Bar"
It's possible to filter the result?

**Comment by nticaric** [comment]
Maybe you should use the TNTSearch implementation without the scout driver.  The method you're
looking for is called `searchBoolean()`. Take a look at http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5
