### ISSUE TITLE
The index file on the server is smaller 

### ISSUE THREAD

**Issue by alkhachatryan** [teamtnt/laravel-scout-tntsearch-driver#205]
Hi. I've imported the model in my localhost and got an index 700MB.
Did the same on the server and got an index file 68MB size.

I'm searching TEST on the localhost and get 450 results
I'm searching TEST on the server and get 40 results

Made a small function, that's counting the second for importing on the server - max 260 second. When run up to 260, the command finishes, but the import dont get all data from a table.

On localhost it gets ~ 5-6 mins to index, on the servers it stop when 260s.

I'm using:
DB: Postgresql
Live server: CENTOS with WHM
Localhost: Ubuntu
The table with big data contains: 600K records

**Comment by nticaric** [comment]
The first thing I would say is that your local and production databases are different. Try to delete the index file and index it from scratch

**Comment by alkhachatryan** [comment]
> The first thing I would say is that your local and production databases are different. Try to delete the index file and index it from scratch

There are the same DBs

**Comment by alkhachatryan** [comment]
Any one?

**Comment by ultrono** [comment]
I've used TNT a lot and haven't run into this before. Have you attempted importing the data manually via the cli using the TNT specific import command instead of Scout? i.e. `php artisan tntsearch:import App\\Post`

**Comment by alkhachatryan** [comment]
@ultrono yap.
