### ISSUE TITLE
Composer fails with Scout version 6 already installed

### ISSUE THREAD

**Issue by jameswagoner** [teamtnt/laravel-scout-tntsearch-driver#206]
Any issues with updating the Scout version requirements?

**Comment by jenky** [comment]
In the 6.0 version `Laravel\Scout\Engines\Engine` has new abstract method [`flush`](https://github.com/laravel/scout/compare/v5.0.3...v6.0.0#diff-c0a1ec7dbf011155e6c41c1f05d39fffR76) that need to be implemented

**Comment by nticaric** [comment]
new version is out that should work fine with latest scout
