### ISSUE TITLE
Is version 5.7 supported as well?

### ISSUE THREAD

**Issue by Shifterovich** [teamtnt/laravel-scout-tntsearch-driver#207]
If yes, then the readme should be updated.

**Comment by vimalmistry** [comment]
Yes. Package is not installing in 5.7 :(

**Comment by ultrono** [comment]
Yep, same here, just randomly noticed when doing an upgrade :/

**Comment by seanareed** [comment]
I'm getting this output when trying to install using Laravel 5.7.11, PHP 7.2.11, Scout ^6.1, and composer 1.7.2:

```
$ composer require teamtnt/laravel-scout-tntsearch-driver
Using version ^3.3 for teamtnt/laravel-scout-tntsearch-driver
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/scout[5.0.x-dev, v6.1.1].
    - Can only install one of: laravel/scout[v6.1.1, 5.0.x-dev].
    - Can only install one of: laravel/scout[5.0.x-dev, v6.1.1].
    - teamtnt/laravel-scout-tntsearch-driver v3.3.0 requires laravel/scout 5.0.* -> satisfiable by laravel/scout[5.0.x-dev].
    - Installation request for teamtnt/laravel-scout-tntsearch-driver ^3.3 -> satisfiable by teamtnt/laravel-scout-tntsearch-driver[v3.3.0].
    - Installation request for laravel/scout (locked at v6.1.1, required as ^6.1) -> satisfiable by laravel/scout[v6.1.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by ultrono** [comment]
Odd, a fresh install fetched laravel/scout v5.0.3 for myself. I have a project with Scout I need to upgrade to laravel 5.7 next week. I'll feedback my findings here.

Try running:

`composer remove teamtnt/laravel-scout-tntsearch-driver`

and ensure the `laravel/scout` package has been removed too. Then try an install as you have above. 

The TNT driver appears to require v5 of Scout, that's what causing the above error.

What's your output of `composer why laravel/scout`?

**Comment by seanareed** [comment]
Scout 6 is what was automatically installed when I ran `composer require laravel/scout` as described in the docs for Laravel 5.7.

Running `composer why laravel/scout` gives me:

`laravel/laravel  dev-dev  requires  laravel/scout (^6.1)`

**Comment by seanareed** [comment]
I don't understand that either. I don't believe I'm using a develop or pre-release branch of Laravel. I'm quite sure I installed it using composer as described in the Laravel 5.7 docs.

When I create a new local git branch for the project and run `composer why` again, the output says `laravel/laravel  dev-newbranch  requires  laravel/scout (^6.1)`, so part of the output is apparently coming from the name of the git branch.

**Comment by nticaric** [comment]
I new version is out that should cover laravel scout 6.*
