### ISSUE TITLE
error install teamtnt in xampp php 7.2.10

### ISSUE THREAD

**Issue by zakkytaufiqurrohman** [teamtnt/laravel-scout-tntsearch-driver#209]
i use win 10 and xampp php version 7.2.10, and laravel scout v 6 .i have a error when install  
Problem 1
    - Installation request for teamtnt/laravel-scout-tntsearch-driver ^3.3 -> satisfiable by teamtnt/laravel-scout-tntsearch-driver[v3.3.0].
    - teamtnt/laravel-scout-tntsearch-driver v3.3.0 requires laravel/scout 5.0.* -> satisfiable by laravel/scout[5.0.x-dev, v5.0.0, v5.0.1, v5.0.2, v5.0.3] but these conflict with your requirements or minimum-stability.

how to solve it?

**Comment by ultrono** [comment]
I've literally just installed from scratch on Laradock with PHP 7.2, without issue, see https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/207#issuecomment-441478811

**Comment by seanareed** [comment]
I think this was addressed and fixed as described in #207 and #206.
