### ISSUE TITLE
Problem with join query

### ISSUE THREAD

**Issue by d4rkr3pt0r** [teamtnt/laravel-scout-tntsearch-driver#210]
Hi,
I have 3 tables with the following structure : 

```
posts (Post Model -> belongsToMany('App\Category')):
id     title    body
--------------------------
categories (Category Model -> belongsToMany('App\Post')):
id     title
--------------------------
category_post
category_id     post_id
```

My question is how can I write a query to search using multiple inputs? for example I wanna search for a post with the title of "Hello world" which belongs to categories with ids of (1 and 2).

Any help would be greatly appreciated

**Comment by mdnpro** [comment]
I could achieve this using constrains but faced with another problem. [Here](https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/211)
