### ISSUE TITLE
Include TNTSearch score in model instances

### ISSUE THREAD

**Issue by enrikas** [teamtnt/laravel-scout-tntsearch-driver#222]
I'm conscious that TNTSearchEngine has a scoring parameter.  I'd quite like it so i can score results im performing on two seperate models and decide what to show.

Is there a way (that i'm missing), or has anyone some thoughts on how i might expose this value through scout?

**Comment by pedzed** [comment]
Have you found any solution? I am interested as well.

**Comment by it4need** [comment]
Push. Does anyone know how to make this work? I'm also using multiple models, show them together in one search and order them by score.
