### ISSUE TITLE
Memory error when having a ")" in the search without a "("

### ISSUE THREAD

**Issue by kderoode** [teamtnt/laravel-scout-tntsearch-driver#225]
Hello,
I get the following error when i include a closing parentheses in a search without first having an open parentheses:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 100663304 bytes) in ...\vendor\teamtnt\tntsearch\src\Support\Expression.php on line 22

**Comment by pet1330** [comment]
+1 
I am also experiencing this issue
