### ISSUE TITLE
Results Limited

### ISSUE THREAD

**Issue by sonnysavage** [teamtnt/laravel-scout-tntsearch-driver#234]
I've found when searching with Laravel Scout that only the first 500 results are returned. I've looked at the SQLite database that the TNTSearch indexing creates, and it has far more than 500 matches.

```sqlite
SELECT COUNT(DISTINCT doclist.doc_id)
FROM wordlist
JOIN doclist ON doclist.term_id = wordlist.id
WHERE wordlist.term = 'qui'
```

The above query returns `1139`.

This: `Model::search('qui')->get()->count()` returns `500`.

I've been unable to locate where the limit of `500` is coming from. I thought it might be the chunking settings in `config\scout.php`, but changing those values doesn't affect my output.

The driver class (`vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php`) has these lines:

```php
    protected function performSearch(Builder $builder, array $options = [])
    {
        $index = $builder->index ?: $builder->model->searchableAs();
        $limit = $builder->limit ?: 10000;
```

The `$builder->limit` is set by the `take()` function. The code leads me to believe that I would get up to 10,000 results if I didn't define a limit. However, this: `Model::search('qui')->take(750)->get()->count()` still returns `500`.

In the end, I want to get the entire result set, but I can't even get past changing the limit.

**Comment by nticaric** [comment]
The limit is set here:

https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L19

Not sure if you can set it via scout
