### ISSUE TITLE
Add Geo/FindNearest

### ISSUE THREAD

**Issue by r0bdiabl0** [teamtnt/laravel-scout-tntsearch-driver#235]
Do you plan on adding geo/findnearest to your scout driver?

**Comment by nticaric** [comment]
I think it's easy enough to use the TNTSearch package directly

**Comment by r0bdiabl0** [comment]
There was a recommendation a few years back. What do you think about it? 

https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/28#issuecomment-306268175

**Comment by user00265** [comment]
Modifying the engine using some version of [#28 (comment)](https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/28#issuecomment-306268175) to be able to do a search callback as outlined under _**Customizing Engine Searches**_ [on the Scout docs](https://laravel.com/docs/5.8/scout#searching) would probably be the way of least resistance for this to be added.
