### ISSUE TITLE
Add support for Laravel 6.0

### ISSUE THREAD

**Issue by Dylan-Chapman** [teamtnt/laravel-scout-tntsearch-driver#243]
Package currently only supports Laravel 5.4.x-5.8.x, need to add compatibility with 6.x.

**Comment by MarceauKa** [comment]
https://packagist.org/packages/marceauka/laravel-scout-tntsearch-driver

**Comment by user00265** [comment]
> This is my fork. It's only compatible with Laravel >= 6.0
> 
> https://github.com/MarceauKa/laravel-scout-tntsearch-driver

It looks like you modified `composer.json` to obtain compatibility, but you just replaced all the previous version strings with just the newer ones. Why not actually "or" them following the same versioning that is already available instead of just making it backwards incompatible?

**Comment by user00265** [comment]
And as I say that, I saw commit 580c77b4f93e5a5b5a27f55f8224679870e59625 which adds support for Laravel 6.0
