### ISSUE TITLE
Index file on cloud?

### ISSUE THREAD

**Issue by praveenselvam** [teamtnt/laravel-scout-tntsearch-driver#245]
I'm using laravel on the Google app engine, which doesn't permit writing to the disk, or persistence of files across deployments. This doesn't help when it comes to indexing and storing the file locally. Is there a way to use the cloud storage for the index file, so that it can be persisted across deployments?

**Comment by ultrono** [comment]
I had a similar situation. I had a single admin area controlling multiple websites, that ran off an API. Each website needed to search a different index.

Initially I hosted the index files on my api. However, this made unecessary api requests when no products were found.

Ultimately I decided to host the actual index directly on each site and then send up a list of product ids for my API to return.

I have a console command on my API that refreshes the search indexes twice daily. The index is pushed to AWS S3. Each site then has a console command that pulls down the latest copy of the index from S3.

**Comment by moyvera** [comment]
I saw that the code of tntsearch can be modified easily to support external sqlite database. (Of course, we need a PR) 

I was facing this issue too and for a quick solution I had to mount one common filesystem where all the instances of my application have access. (This is not the best approach, but when I get time, I will separate this section to work as a microservice)

For you I think the best option is to write a PR to support this feature...  Because you don't have where to write files :/

**Comment by flexgrip** [comment]
Did anyone figure this out? Same boat. Appengine can only write tmp files to memory. Seems like my only two options are to build and include in the index on deploy, or to somehow detect when a new instance is created and fire off the command to build the index and throw it in memory. Hmm...

**Comment by Cranavvo** [comment]
> Did anyone figure this out? Same boat. Appengine can only write tmp files to memory. Seems like my only two options are to build and include in the index on deploy, or to somehow detect when a new instance is created and fire off the command to build the index and throw it in memory. Hmm...
> 
> Or... if instead of `'storage' => storage_path()` we could store use `'storage' => Storage::disk('gcs')`, that would easily solve the problem. Just dump the files to gcs. For a small index, it should be fast enough.

This is the same for Heroku's ephemeral file system.

You can store temporary files, however, because of the way 'dynos' work, they revert back the same file as pushed during production.

S3/MongoDB support might be something to look at.

**Comment by ultrono** [comment]
> Cannot get it to work....
> 
> ```
> 'storage' => Storage::disk('s3')
> ```
> 
> When using Scout any way possible, it tells me ;
> 
> ```
> In Facade.php line 258:
>                                                                        
>   A facade root has not been set.                                      
>                                     
> ```
> 
> I didn't achieve to load the facade before it's use either

That won't work because the underlying TNTSearch engine expects a string, see https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L37
