### ISSUE TITLE
Automatic syncing?

### ISSUE THREAD

**Issue by AshotN** [teamtnt/laravel-scout-tntsearch-driver#255]
I don't understand if this package automatically handles database changes in the index. Can anyone explain how it works, and what we are expected to do.

**Comment by emielmolenaar** [comment]
That is explained here: https://laravel.com/docs/6.x/scout .

**Comment by AshotN** [comment]
Can you tell me what file permissions the index files need to have.

**Comment by emielmolenaar** [comment]
Well I guess they have to be writable in some way by the user which PHP runs as.

**Comment by Namoshek** [comment]
The directory where the indexes are stored in needs to have read, write and execute permissions. The index files themselves only need read and write permissions for the user or a group under which your queue workers run.
