### ISSUE TITLE
orderBy()  + paginate() = sorts per page?

### ISSUE THREAD

**Issue by tanthammar** [teamtnt/laravel-scout-tntsearch-driver#260]
- Scout Version: 7.2.1
- Laravel Version: 6.9.0
- PHP Version: 7.3.11
- Database Driver & Version: "teamtnt/laravel-scout-tntsearch-driver": "^7.2"
- MySQL 5.7.24

**Description:**
Using orderBy() with paginate() gives a strange result.
Looks like it is sorting per paginated page and not across the entire search result.

**Steps** To Reproduce:
```php
->search($search)
->orderBy('id',  'asc')
->paginate()
```

**Comment by 0plus1** [comment]
I have the exact same issue.
When using pagination, the package returns inconsistent results as the order is almost random.

**Comment by novocent** [comment]
+1

**Comment by sevbauer** [comment]
Same here

**Comment by tarreislam** [comment]
You can overcome this by using 1 query to search, pluck those ids, then query the same model again with "whereIn"

something like this

```php
$ids = User::search("Ben st")->pluck('id');

return User::whereIn('id', $ids)->orderBy('name')->paginate(25);

```

**Comment by MostafaRabia** [comment]
same here...

**Comment by MostafaRabia** [comment]
@tarreislam 
Method Laravel\\Scout\\Builder::pluck does not exist.
And it's not good too, why using one more line and calling database?

**Comment by tarreislam** [comment]
> Method Laravel\Scout\Builder::pluck does not exist.

 my bad, you have to get the collection first. 
`$ids = User::search("Ben st")->get()->pluck('id'); `

> And it's not good too, why using one more line and calling database?

:)

**Comment by MostafaRabia** [comment]
@tarreislam 
not your bad, but we need to fix it, thank you for your help.

**Comment by MostafaRabia** [comment]
I searched on source of package, and i realized that this line in: Engines/TNTSearchEngine.php
`$chunks = array_chunk($filtered->toArray(), $perPage);`
was the problem.
For that it's per page not in whole database, and i checked query by query log and it's correct.
And if you returned `$results` after `$filtered = $this->discardIdsFromResultSetByConstraints($builder, $results['ids']);` it will back all data in your correct order.

So i turned it to:
`$filtered_array = $filtered->toArray();
        if ($this->builder->orders[0]['direction']==="desc"){
            rsort($filtered_array);
        }

$chunks = array_chunk($filtered_array, $perPage);`
will check if order is desc is desc or not, and resort it.

If you ckeck by `return $results;` it will show your correct order as i said, but code `$chunks = array_chunk($filtered->toArray(), $perPage);` without resort it, will chunk just from the first, so it's show in per page order.

Now i tested that:
`$chunks = array_chunk($filtered->toArray(), $perPage);
        if ($this->builder->orders[0]['direction']==="desc"){
            rsort($chunks);
        }`
i returned it to original, and just resort the $chunks if the order is desc, and worked too.

The idea is resort the results if your order is desc, that's worked for me, Sorry for my bad english but i hope i did somthing useful.
