### ISSUE TITLE
TNTSearchEngine::map() returns BaseCollection instead of Database collection.

### ISSUE THREAD

**Issue by ozanyolyapar** [teamtnt/laravel-scout-tntsearch-driver#261]
I was trying to use load() on the returned collection by get(). Tinker throws the following:
```bash
>>> Device::search("huawei smart")->get()->load()
BadMethodCallException with message 'Method Illuminate/Support/Collection::load does not exist.'
```

I have found out, that you are using the collect() function on the result, which returns Illuminate\Support\Collection instead of the Illuminate\Database\Eloquent\Collection like expected and defined in the phpdoc of the function TNTSearchEngine::map().

Quote from [Laravel Docs](https://laravel.com/docs/6.x/eloquent-collections):

> All multi-result sets returned by Eloquent are instances of the Illuminate\Database\Eloquent\Collection object, including results retrieved via the get method or accessed via a relationship. The Eloquent collection object extends the Laravel base collection, so it naturally inherits dozens of methods used to fluently work with the underlying array of Eloquent models.

However, paginate function works as expected. My current workaround is to iterate over the base collection and lazy load the relationship, which generates too much queries. To limit queries, I use now `take()`.
```php
$devices = Device::search("huawei smart")->take(10)->get();
foreach($devices as $device){
    $device->load("vendor");
}
```

**Comment by Namoshek** [comment]
Why don't you simply wrap the results you get after calling `get()` on the builder with your own Eloquent collection?

```php
$devices = \Illuminate\Database\Eloquent\Collection::make(
    Device::search("huawei smart")->take(10)->get()
);
$devices->load('vendor');
```

But I agree, this should be changed in an upcoming version. As `Illuminate\Database\Eloquent\Collection` only extends `Illuminate\Support\Collection`, it should be a fully backwards compatible change.
