### ISSUE TITLE
Index is not working as should be

### ISSUE THREAD

**Issue by josegus** [teamtnt/laravel-scout-tntsearch-driver#264]
When i run tntsearch:import "App\Models\Product", the conditional function shouldBeSearchable() is working but is being ignored. I've hardcoded the shouldBeSearchable function to false, but the model is sill being indexed. 

My app is not cached.
Develop on local machine with Ubuntu 16, php 7.2 and laravel 6.12

**Comment by pravo-pro** [comment]
Hi, no changes there? get same trouble
may be some one know how fix by hardoce / timefix
