### ISSUE TITLE
Cannot configure queuing with SQS

### ISSUE THREAD

**Issue by davehowson** [teamtnt/laravel-scout-tntsearch-driver#265]
Hello,
I have deployed my Laravel App to Amazon Elastic Beanstalk and configured the app to work with S3 for storage and SQS for queuing. 
Laravel-scout-tntsearch-driver sends a message to the queue which I can monitor from the SQS console, but it does not create the index file in S3 or Elastic Beanstalk storage.
Is there any way I can get this fixed?

Thank You

**Comment by Namoshek** [comment]
I've no answer to your actual question, but I doubt using cloud storage will yield good performance with a search index which is used frequently. Only when you utilize the caching capabilities for filesystems, this might work out as expected.
