### ISSUE TITLE
The keys are passed as a collection and not as an array inside the map function

### ISSUE THREAD

**Issue by ba77osai** [teamtnt/laravel-scout-tntsearch-driver#27]
In the file [TNTSearchEngine.php#152](https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L152) in the map function, the keys are collected inside a collection and not as an array like in the examples from Laravel ( [ElasticSearch#L233](https://github.com/laravel/scout/blob/master/src/Engines/ElasticsearchEngine.php#L233) )

That behaviour makes problems with other implementation, (example laravel-doctrine: [Laravel-Doctrine#L141](https://github.com/laravel-doctrine/scout/blob/master/src/SearchableRepository.php#L141) ) where an array is expected.

Would it make a big problem to replace the keys to a normal array instead a collection?

**Comment by nticaric** [comment]
No problem, please create a pull request and we'll merge it.

**Comment by nticaric** [comment]
Thanks for the PR
