### ISSUE TITLE
Search multiple models paginated

### ISSUE THREAD

**Issue by OscarFCN** [teamtnt/laravel-scout-tntsearch-driver#276]
Hi, I need to create a search on multiple independent models paginated. Is there any way to do this? I didn't found anything how to do it.

Thanks

**Comment by timgavin** [comment]
Here's what I did. Probably isn't the best way but it works...

Import the models you want to search

```
php artisan scout:import App\\Models\\Post
php artisan scout:import App\\Models\\Testimonial
```

Set up the `toSearchableArray()` in your model as normal, then in your controller perform a search against each model and merge them together into a single collection.

```
class SearchController extends Controller
{
    public function show(Request $request)
    {
        $term = $request->term;

        $posts = Post::search($term)->get();
        $tests = Testimonial::search($term)->get();

        $results = $posts->merge($tests);

        return view('search.show', compact('results', 'term'));
    }
}
```

If your models use the same column names, such as `title` and `body`, you can use Laravel's `getTable()` method to get the table name and edit your layout accordingly.

```
@foreach($results as $result)
    
    @if($result->getTable() == 'posts')
        <!-- from the POST model -->
    @endif
    
    @if($result->getTable() == 'testimonial')
        <!-- from the TESTIMONIAL model -->
    @endif

@endforeach
