### ISSUE TITLE
How to get highlighted match result ?

### ISSUE THREAD

**Issue by gary101** [teamtnt/laravel-scout-tntsearch-driver#277]
I want to apply this to my website api but can not figure out how to get highlighted match result ,

How should I do to do result highlight?

Thanks a lot!

**Comment by nticaric** [comment]
Here's an example on how to use the highlighter

https://github.com/teamtnt/tntsearch-demo/blob/51e6ccc11168dc06f8cd837be1b5cda3e0518a1b/app/Http/Controllers/SearchController.php

lines 89 and 93

**Comment by gary101** [comment]
Hi @nticaric, thanks a lot for your reply, I make it after refer to the link you gave me and the source code of tntsearch.

I think is good to give the code below as reference to others(actually from source code  tntsearch\tests\support\HighlighterTest.php):

> use TeamTNT\TNTSearch\Support\Highlighter;
> $hl  = new Highlighter;
> $output = $hl->highlight($text, "this text", 'em', ['caseSensitive' => true]);
> $this->assertEquals("This is some <em>text</em>", $output);

Thanks again!
