### ISSUE TITLE
No results for simple search

### ISSUE THREAD

**Issue by dimzeta** [teamtnt/laravel-scout-tntsearch-driver#281]
When I do a search starting at the beginning of the word, it works, but when I enter a term in the middle of the word, I get no results.

For example, I have a Model with the name "Dominique Maury".

If I do a search by typing "Domi", "domi", "dom", I have my Model in my results.
If I search for "omi", "mini", "que", I have no results.

It also works with "mau", "Mau", "Maur", but not for "aur", "aury".

It seems really strange that it doesn't work for such a simple search. Did I forget/do something wrong?

Here is my config:

```php
    'tntsearch' => [
        'storage'  => storage_path(),
        'fuzziness' => true,
        'fuzzy' => [
            'prefix_length' => 2,
            'max_expansions' => 50,
            'distance' => 2
        ],
        'asYouType' => true,
        'searchBoolean' => false,
        'stemmer' => \Wamania\Snowball\Stemmer\French::class,
    ],
```

I tried with and without the French stemmer, same result.

**Comment by oceceli** [comment]
I have the same problem. Did you find any solution? Or anyone?

**Comment by dimitribocquet** [comment]
@oceceli Nope. I rollback to a simple MySQL search.

**Comment by simion-chis** [comment]
I don't know if this apply to your scenario. In my case I have imported models with ```php artisan scout:import "App\Models\ModelName"``` and after import ```php artisan queue:listen```. At import, jobs are placed in queue
