### ISSUE TITLE
Not adding new records to index

### ISSUE THREAD

**Issue by gwaliclub** [teamtnt/laravel-scout-tntsearch-driver#282]
###  I started using Tntsearch and i cant see search results for recently created posts
This persists and if i run `php artisan tntsearch:import App\\Post\\Post`, i get this error 
 

> unlink(C:my-project-link/title.index): Resource temporarily unavailable
This persists until i manually delete the title.index file and re-run `php artisan tntsearch:import App\\Post\\Post` .
Only then will i now see my search results.
Meanwhile, on my queues, `Laravel\Scout\Jobs\MakeSearchable` is processed succesfully

**Comment by msoler75** [comment]
Maybe should use

App\\Models\\Post

Not 

App\\Post\\Post
