### ISSUE TITLE
Fuzzy search results are not matching as well as

### ISSUE THREAD

**Issue by MIMAXUZ** [teamtnt/laravel-scout-tntsearch-driver#286]
I am working on a drug search engine. The user cannot always enter the exact drug name. Depending on the characters entered by the user, I need to get a better result for him. But now it is not. 
How should I do to do result more accurately?
For example, there is information in db: `Анальгин, Цитрамон-П,  Лирика-75мг`, etc. ... (in Crylic). If the user enters in the Latin alphabet, the system converts it to the Cyrillic alphabet and searches through it. 
So I need that:  Even if the user enters words in  `Цитрамон, cитрамон, ииттрамон or cтрамон`, the result should return `Цитрамон`. Or if user enter: `Лирика, ЛЛЛирика, иииррика, Лика or Лирик`, the result should return `Лирика`. Or  `Аналгин, Анагин` should returns `Анальгин`. 
How can I get such a result? I tried several packages but to no avail. Now even if I use the TNTSearch package, it works just like the `Like operator`. only finds the word that is clearly entered (Цитрамон finds Цитрамон, it was not found итрамон).
Now my model:
```
 public function toSearchableArray()
    {
        $array = $this->only('id', 'name');
        return response()->json($array);
    }
```
And my controller:
```
  public function search(Request $request)
    {
        $data = [];
            //dd($request->all());
            $search = _ltc($request->qry); // Convert Latin letters to Crylic 
            $data = Drug::search($search)
            ->paginate(15);
         
        return response()->json($data);
    }
```
Can anyone help?
Thanks a lot!

**Comment by nticaric** [comment]
TNTSearch has support for typo tolerance but you have to enable it in your config. It's called `fuzziness` and needs to be set to true like this:

```php
'tntsearch' => [
    'storage'  => storage_path(), //place where the index files will be stored
    'fuzziness' => true,
    'fuzzy' => [
        'prefix_length' => 2,
        'max_expansions' => 50,
        'distance' => 2
    ],
    'asYouType' => false,
    'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
],
```

Fuzzines has some options you can play with to get best results. The `prefix_length` option tells you how many first letters need to be an exact match. In the above example its set to 2. This means that the user MUST enter the first 2 letters correctly,
and and since the `distance` is set also to 2, he is allowed to make only 2 typos.

If you assume that the user will enter the first two letters also wrong, you have to use a different approach like n-grams

Hope this helps

**Comment by MIMAXUZ** [comment]
@nticaric Thanks a lot, yes you seem to understand the problem in me.  I tried the solution you gave me. The downside is that the user can also enter the first letters incorrectly. As far as I understand, n-gram can help as you say, but I searched the tutorials and couldn’t find a definite solution. Here I found (https://tnt.studio/blog/did-you-mean-functionality-with-laravel-scout), but the tutorial and the repo on GitHub do not match.  Can you give me any advice on how to use n-grams with TNTSearch? There is no clear information in the doc either.
Thanks again!

**Comment by nticaric** [comment]
If you're still stuck with this we offer premium support for TNTSearch. Simply drop us an email to info@tntstudio.hr
