### ISSUE TITLE
toSearchableArray() without ID get error

### ISSUE THREAD

**Issue by thewebartisan7** [teamtnt/laravel-scout-tntsearch-driver#291]
If you omitt the ID from toSearchableArray() then there is an error, and is fixed only when add ID.

Error:

```
 ErrorException 

  Undefined index: id

  at vendor/teamtnt/tntsearch/src/Support/Collection.php:96
     92|     }
     93| 
     94|     public function get($key)
     95|     {
  >  96|         return $this->items[$key];
     97|     }
     98| 
     99|     /**

```

**Comment by nticaric** [comment]
That's, correct. An unique identifier is required. By default it's the id field, but it can be anything that is unique.

**Comment by thewebartisan7** [comment]
@nticaric how to change to another key?

Because I add:

```

    /**
     * Get the value used to index the model.
     *
     * @return mixed
     */
    public function getScoutKey()
    {
        return $this->email;
    }

    /**
     * Get the key name used to index the model.
     *
     * @return mixed
     */
    public function getScoutKeyName()
    {
        return 'email';
    }
```

But still require ID.

Cao

**Comment by nticaric** [comment]
It's because your primary key is set to be an ID. If you change the primary key to something different, then it will work

In your model:

`protected $primaryKey = 'email';`

**Comment by thewebartisan7** [comment]
I see you set primary key from model primary key:

`$index->setPrimaryKey($models->first()->getKeyName());`

Why not use getScoutKey() since it's possible to do that with scount (https://laravel.com/docs/8.x/scout#configuring-the-model-id)?

Anyway it's not big problem.. I just think that also primary key will be indexed since must be returned by toSearchableArray, but seem not, if I try search by ID no result it's found
