### ISSUE TITLE
Getting Limited results on search

### ISSUE THREAD

**Issue by gsofficework** [teamtnt/laravel-scout-tntsearch-driver#296]
Hi, 

While I'm using this package, I encountered an error of getting limited results.
----
**Issue:**

Search keywords:  '2020' or '345', or '2020A000017' (see below),

1. `Case::search('2020')->get();` - **Result:** Only **one** result with last records [id = 100, case_number = 2020A000003]
2. `Case::search('345')->get();` - **Result:** **NO results**
3. `Case::search('2020A000017')->get();` - **Result:** [id = 88, case_number = 2020A000017]
4. `Case::search('n7D')->get();` - **Result:** **NO results**

-----
**My Code and Database**
I have a database table `cases` with `id` and `case_number` columns and sample data as below:

```
id       case_number
---     ---------------
88       2020A000017
91       2020A0000021n7D
99       2020A00005345
100      2020A000003

```

**File: config/scout.php**
```
    tntsearch' => [
        'storage'  => storage_path(), //place where the index files will be stored
        'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
        'fuzzy' => [
            'prefix_length' => 2, 
            'max_expansions' => 50,
            'distance' => 2
        ],
        'asYouType' => true,
        'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
    ],
```

**My model file (Case.php)**
```
    public function toSearchableArray() {
        return $array =  [
            'id'    => $this->id,
            'case_number' => $this->case_number,
        ];
    }
```
-----
***Steps I have tried***

1. Imported fresh data many times using the command `php artisan scout:import App\\Models\\Case`
2. Cleared cache and everything using artisan commands.

----
**What I Found while I was debugging core package files.:**

**In the below function when I remove `limit 1`, then I get all the results as expected. Is this an error in the code or have I misunderstood something?**

_File: projectname\vendor\teamtnt\tntsearch\src\TNTSearch.php_
```

    public function getWordlistByKeyword($keyword, $isLastWord = false)
    {
        $searchWordlist = "SELECT * FROM wordlist WHERE term like :keyword limit 1";
        $stmtWord       = $this->index->prepare($searchWordlist);

        if ($this->asYouType && $isLastWord) {
            $searchWordlist = "SELECT * FROM wordlist WHERE term like :keyword ORDER BY length(term) ASC, num_hits DESC limit 1";
            $stmtWord       = $this->index->prepare($searchWordlist);
            $stmtWord->bindValue(':keyword', mb_strtolower($keyword)."%");
        } else {
            $stmtWord->bindValue(':keyword', mb_strtolower($keyword));
        }
        $stmtWord->execute();
        $res = $stmtWord->fetchAll(PDO::FETCH_ASSOC);

        if ($this->fuzziness && !isset($res[0])) {
            return $this->fuzzySearch($keyword);
        }
        return $res;
    }
````

Please can anyone help me with this?

Thank you in advance.

**Comment by nticaric** [comment]
Fulltext search doesn't behave like a `LIKE` operator in SQL. You either have to use the full phrase while searching
or you have to implement `n-grams`

**Comment by gsofficework** [comment]
Thank you for the response.

But when I try the incomplete phrase 'tes', I get results contains "test", but when I try '2020' I don't get results.

But when I remove the `limit 1` from the above code, it works and I'm getting results that contain '2020' (Like 2020a54, 2020f5875)

Please can you help with this?

**Comment by stokic** [comment]
That’s because “test” is a word ie. text, while 202049shshs is not a word
in any language...

Fuzzy search AND a custom stemmer might help here but not that those
examples are not a text. Full text search primarily works on text and there
are specific stemmers for specific languages for a reason....
