### ISSUE TITLE
PDOException could not find driver

### ISSUE THREAD

**Issue by giantthinker** [teamtnt/laravel-scout-tntsearch-driver#297]
I get this error in production ```$this->index = new PDO('sqlite:'.$this->config['storage'].$indexName);```
How can it be solve?

**Comment by stokic** [comment]
https://lmgtfy.app/?q=PDOException+could+not+find+driver

**Comment by giantthinker** [comment]
@stokic I have done that. Searched for hours if not days.
I just decided to seek help here.

**Comment by giantthinker** [comment]
I solved by installing `sqlite` in production.

**Comment by stokic** [comment]
Seems like you are missing sqlite pho driver. What steps did you take to
try and fix it?

**Comment by giantthinker** [comment]
@stokic I had no sqlite in my production environment and installing sqlite solved the problem.
