### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by mnoquiao** [teamtnt/laravel-scout-tntsearch-driver#298]
Hi! I am having this problem when trying to run scout:import any help?

![image](https://user-images.githubusercontent.com/1167440/94528847-89b48f00-026b-11eb-8c18-38d40966bfe8.png)

**Comment by stokic** [comment]
which versions of everything you are running? (nginx, php, laravel, tntsearch package). what does your config look like. which steps did you take to try and fix this?

**Comment by mnoquiao** [comment]
Hi!

I'm using the following
Nginx (1.18.0)
PHP (7.4.9)
Laravel 8

I read that others successfully fixed the issue by just runing "php artisan config:cache" doesn't work for me though, I just deploy my laravel app on my test machine it works fine except when running scout:import that error occurs.

**Comment by stokic** [comment]
do you have scout.tntsearch config created? php artisan config:clear clears the previously cached config and then it's fresh...

**Comment by mnoquiao** [comment]
Hi yes I already created the config.

**Comment by nticaric** [comment]
Can you try the following and post the results here?
In your routes wile add:

```php

Route::get('dump', function () {
    $driver = config('database.default');
    dd(config("scout.tntsearch"), config("database.connections.{$driver}"));
});


```

**Comment by nticaric** [comment]
If one of those is null, try to run:
```bash
php artisan cache:clear
php artisan config:cache
php artisan config:clear
```

**Comment by mnoquiao** [comment]
Thank you for the help @nticaric that solves my problem.

**Comment by mnoquiao** [comment]
Ops I almost forgot also thanks @stokic !
