### ISSUE TITLE
 Driver [mysql] not supported. 

### ISSUE THREAD

**Issue by ahmetbarut** [teamtnt/laravel-scout-tntsearch-driver#299]
I am installing and configuring teamtnt but **"Driver [mysql] is not supported."** It gives an error but I am using postgresql I tried mysql it gave the same error

**Comment by vahidalvandi** [comment]
why in tntsearch https://github.com/teamtnt/tntsearch#custom-tokenizer driver=mysql 

and this project not support ?

**Comment by nticaric** [comment]
If you are using Laravel scout, the driver needs to be `tntsearch`

**Comment by stokic** [comment]
Please report the problem, if there is one, like it should be reported. What did you try, what steps did you take to fix the problem etc... also with code/error messages etc. 

From what little info was provided it seems that it has nothing to do with package but just not reading the docs. If I'm mistaken, again report the issue with all things that can help debug it.

**Comment by vahidalvandi** [comment]
@stokic , i want use mysql instance sqllike because i have database with huge rows . mysql is powerful of sqllite

**Comment by stokic** [comment]
you misunderstand how tntsearch works... it always uses sqlite for it's indexes. Doesn't matter if it's scout driver or standalone version, indexes are always stored in sqlite. What you use as your database doesn't make a difference here.
So simply: your database = mysql, tntsearch indexes = sqlite

**Comment by vahidalvandi** [comment]
sqlite have good performance in 100K records?

**Comment by stokic** [comment]
try it, it takes a few minutes or check the demo

**Comment by vahidalvandi** [comment]
thank you where is demo ?

**Comment by stokic** [comment]
Unless there is a clear description of the problem, steps to reproduce, steps taken to fix the problem the issue will be closed
