### ISSUE TITLE
Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by Briareos17** [teamtnt/laravel-scout-tntsearch-driver#300]
I have an E_NOTICE when no index file found.
`/src/Engines/TNTSearchEngine::map()`
"Trying to access array offset on value of type null" in $results variable

I see exception, but it's not trowing to top, so $results become null except of empty array.

**Comment by DrowningElysium** [comment]
Fixed in https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/302
