### ISSUE TITLE
Featuretest fails

### ISSUE THREAD

**Issue by MathiasWeisheit** [teamtnt/laravel-scout-tntsearch-driver#301]
Hi, great work! 
I have a problem after successfull integrating the lib.
My featuretests on the model, witch is now "searchable" doesn't work anymore.  Do you have an idea?

Here is the result:
1) Tests\Feature\ProductTest::a_product_can_be_patched
InvalidArgumentException: Driver [tntsearch] not supported.

/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119
/app/vendor/laravel/framework/src/Illuminate/Support/Manager.php:90
/app/vendor/laravel/scout/src/EngineManager.php:23
/app/vendor/laravel/scout/src/Searchable.php:264
/app/vendor/laravel/scout/src/Jobs/MakeSearchable.php:42
/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/app/vendor/laravel/framework/src/Illuminate/Container/Util.php:37
/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:596
/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:83
/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:85
/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:59
/app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:98
/app/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php:43
/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:182
/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:158
/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:73
/app/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:134
/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:391
/app/vendor/laravel/scout/src/Searchable.php:68
/app/vendor/laravel/scout/src/Searchable.php:42
/app/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:114
/app/vendor/laravel/scout/src/Searchable.php:154
/app/vendor/laravel/scout/src/ModelObserver.php:69
/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:401
/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:226
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:189
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:771
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:742
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:210
/app/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php:202
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:211
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:172
/app/tests/TestCase.php:217
/app/tests/Feature/ProductTest.php:122

[Product.txt](https://github.com/teamtnt/laravel-scout-tntsearch-driver/files/5515916/Product.txt)
[env.txt](https://github.com/teamtnt/laravel-scout-tntsearch-driver/files/5515925/env.txt)
[scout.txt](https://github.com/teamtnt/laravel-scout-tntsearch-driver/files/5515929/scout.txt)

**Comment by nticaric** [comment]
We're glad you like the product! 
From the error, it seems that TNTSearch isn't registered in your providers list. Can you make sure that 
`TeamTNT\Scout\TNTSearchScoutServiceProvider::class` is in `config/app.php`

**Comment by nticaric** [comment]
@MathiasWeisheit, did you manage to resolve this issue?

**Comment by MathiasWeisheit** [comment]
Il will check it

**Comment by MathiasWeisheit** [comment]
```
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */
        TeamTNT\Scout\TNTSearchScoutServiceProvider::class,
        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

    ],
```

**Comment by MathiasWeisheit** [comment]
I can give you temporary access to my project

**Comment by MathiasWeisheit** [comment]
hi, do you have any ideas?

**Comment by nticaric** [comment]
So if I understand correctly, it fails only in the tests, but otherwise, it works?

**Comment by MathiasWeisheit** [comment]
meanwile it works. But I do not know what change is responsible.

Thanks a lot. @nticaric
