### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by davehowson** [teamtnt/laravel-scout-tntsearch-driver#304]
I cannot seem to install this on PHP 8 because of this

` teamtnt/tntsearch[v2.0.0, ..., v2.5.0] require php ~7.1 -> your php version (8.0.0) does not satisfy that requirement.`

**Comment by repat** [comment]
@nticaric Can we somehow help with this?

**Comment by nticaric** [comment]
Check out v11.4.0, it should work on PHP 8
