### ISSUE TITLE
Searching works for numbers but not text past a certain number of records

### ISSUE THREAD

**Issue by CitizenBeta** [teamtnt/laravel-scout-tntsearch-driver#306]
I have the following code which works great:

`Album::search($searchTerms)->where('competition_id', $competition->id)`

However, for competitions 29 and up, searching albums no longer works by text, but does by number. Here's a screenshot of my sqli index:

![Screenshot from 2020-12-23 01-37-07](https://user-images.githubusercontent.com/595049/102968627-3ba5d500-44c2-11eb-977f-318b78c5beb9.png)

A search for m60 for instance, will not work, but a search for 64 does. An album with a name of "Highlights" will not come up with any text combination of those letters, however a different album that says "Men's 64 kg" will work with a search of 64.

Examples:

![Screenshot from 2020-12-23 01-36-56](https://user-images.githubusercontent.com/595049/102968750-73ad1800-44c2-11eb-881f-ec1bd3835f34.png)
![Screenshot from 2020-12-23 01-38-25](https://user-images.githubusercontent.com/595049/102968753-7576db80-44c2-11eb-9c46-25e678d85a6b.png)

Here's my settings:

![Screenshot from 2020-12-23 01-39-20](https://user-images.githubusercontent.com/595049/102968764-79a2f900-44c2-11eb-91fa-516913c49577.png)

Any advice would be greatly appreciated. The only thing I can think of is that past competition 29 or so we do get into having thousands of albums. I don't imagine this would be a problem but it's the only thing I can think of.

**Comment by nticaric** [comment]
I suspect that this is because of the where clause. Can you try searching for those terms without it?

**Comment by CitizenBeta** [comment]
It's hard to tell if the where clause is affecting the results, because without the where clause I get results from other competitions which worked anwyay. Does the where clause modify the results before or after they are searched? What is the best practice way to narrow results?

**Comment by nticaric** [comment]
If you have the competition index in the index then you can try to do a search by simply appending the id to the search query

`Album::search($searchTerms . " " .$competitionId)`

The search engine itself will return 1000 results that match your query, then the where clause is applied which could lead to behaviors like yours where you don't get the full result set

**Comment by CitizenBeta** [comment]
Is there a way to specify a limitation before the search is made? So that it still returns the 1000 results but with the restriction in place? Or. for a text search, to specifiy which field? For instance, in my use case there is a weight class of 85, but a competition id of 85 as well. For the page that they're on, we want to only search for albums within a specific competition.
