### ISSUE TITLE
Laravel scout + tntsearch is returning empty collection while searching with uuid

### ISSUE THREAD

**Issue by timtinan37** [teamtnt/laravel-scout-tntsearch-driver#307]
I'm using laravel scout with tntsearch driver in a laravel 7 project. Scout is always returning an empty collection if I search by id(uuid). But I get search results as expected if I search with fields other than id.

<h2>Controller</h2>

    public function index(Request $request)
    {
        $coverNotes = null;

        if (request('search'))
        {
            $coverNotes = CoverNote::search(request('search'))->paginate(1); // it is always empty while searching with id, which is of 'uuid' type
        }
        else
        {
            $coverNotes = $this->coverNote->paginate(1);
        }

        return View::make('cover-notes.index', compact('coverNotes'));
    }

<h2>Model</h2>

    class CoverNote extends Model
    {
        use Searchable, UuidTrait;
    
        public $asYouType = false;
    
        public function toSearchableArray()
        {
            $array = $this->toArray();
    
            return $array;
        }
    
    }

<h2>config/scout.php</h2>

    'queue' => env('SCOUT_QUEUE', false),  // I didn't set it on .env

    'tntsearch' => [
        'storage'  => storage_path(), //place where the index files will be stored
        'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
        'fuzzy' => [
            'prefix_length' => 2,
            'max_expansions' => 50,
            'distance' => 2
        ],
        'asYouType' => false,
        'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
    ],

<h2>scout:status</h2>

     ---------------------- ------------------- ----------------- --------------- ------------ -------------------- 
      Searchable             Index               Indexed Columns   Index Records   DB Records   Records difference  
     ---------------------- ------------------- ----------------- --------------- ------------ -------------------- 
      App\Models\CoverNote   cover_notes.index                     1               1            Synchronized        
     ---------------------- ------------------- ----------------- --------------- ------------ --------------------

**Comment by kcaj-burr** [comment]
Sounds like:
#219 

https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/219
