### ISSUE TITLE
Extremely slow importing

### ISSUE THREAD

**Issue by filippesic** [teamtnt/laravel-scout-tntsearch-driver#310]
Hello,

I tried to find if anybody already posted similar issue and I found issue #15 to be very similar to mine, just that his solution kinda doesn't work. I'm trying to search about 28k `mediumtext` records which are imported from text files. I tried limiting `toSearchableArray()` to only the field I need, like in that other similar issue, but it doesn't change anything. It's no different than `scout:import`, but I need add `id` field for it to work. Am I missing something, is searching `medimtext` fields the problem or impossible or something else? Or elasticsearch that I used previously is somehow affecting indexing here, but I can't see how is that possible. I'm coming from `elastic-scout-driver-plus` to be specific. I did `scout:flush` before switching as well.

VirtualBox 6.1.16 / Homestead(box version 11.0.0)
Ubuntu 20.04.2 LTS / Linux 5.4.0-65-generic x86_64 kernel
PHP 7.4.15
Laravel 8.28.1
Tntsearch-driver 11.1.0

```Processed 1000 rows``` - 7 minutes 35 seconds

Any help is extremely appreciated.

**Comment by nticaric** [comment]
Have you tried with `tntsearch:import` does it make any difference?Have you tried with `tntsearch:import` does it make any difference?

**Comment by filippesic** [comment]
Yes, both `scout:import` and `tntsearch:import` are similar speeds.
