### ISSUE TITLE
php artisan tntsearch:import ModelName OR php artisan scout:import ModelName both are not working.

### ISSUE THREAD

**Issue by faizan-glowlogix** [teamtnt/laravel-scout-tntsearch-driver#311]
Hi there,

**Help please it urgent..**

I am implementing it. but when ever i run 
**php artisan tntsearch:import ModelName OR php artisan scout:import ModelName**

it gives me this error.
```
 Class 'ModelName' not found

  at C:\laragon\www\project\vendor\teamtnt\laravel-scout-tntsearch-driver\src\Console\ImportCommand.php:37
    33|     public function handle(Dispatcher $events)
    34|     {
    35|         $class = $this->argument('model');
    36|
  > 37|         $model = new $class();
    38|         dd($class);
    39|         $tnt = new TNTSearch();
    40|         $driver = $model->getConnectionName() ?: config('database.default');
    41|

  • A class import is missing: You have a missing class import. Try importing this class: `App\Models\CarIn`.

  1   C:\laragon\www\amjad-motors\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      TeamTNT\Scout\Console\ImportCommand::handle(Object(Illuminate\Events\Dispatcher))

  2   C:\laragon\www\amjad-motors\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      call_user_func_array()
```

Please share what is the problem here...

**Comment by faizan-glowlogix** [comment]
**My packages Details**

> "laravel/framework": "^7.0",
>  "laravel/scout": "^8.6",
>  "teamtnt/laravel-scout-tntsearch-driver": "^11.1"

**Comment by stokic** [comment]
Obviously class not found like the error says.

What steps did you take in order to debug the situation?

**Comment by faizan-glowlogix** [comment]
i am searching on it.. but didn't find anything to debug it.. as my model class working fine in controller and other places.

**Comment by stokic** [comment]
Write here exactly what you enter in the command line and show your folder
structure plus model namespace

**Comment by faizan-glowlogix** [comment]
![image](https://user-images.githubusercontent.com/66687523/108563621-8c4f7800-7323-11eb-9dad-3a45eee84955.png)
My folder Strucutre.. one change i have done it here.. before they were in app directory...  i moved them in Models Directory.

**Comment by faizan-glowlogix** [comment]
After that i run this command 
**composer require teamtnt/laravel-scout-tntsearch-driver**

> Configure this package same as given in the first page.. 
> 
> Add the service provider:
> 
> // config/app.php
> 'providers' => [
>     // ...
>     TeamTNT\Scout\TNTSearchScoutServiceProvider::class,
> ],
> Ensure you have Laravel Scout as a provider too otherwise you will get an "unresolvable dependency" error
> 
> // config/app.php
> 'providers' => [
>     // ...
>     Laravel\Scout\ScoutServiceProvider::class,
> ],
> Add SCOUT_DRIVER=tntsearch to your .env file
> 
> Then you should publish scout.php configuration file to your config directory
> 
> php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"
> In your config/scout.php add:
> 
> 'tntsearch' => [
>     'storage'  => storage_path(), //place where the index files will be stored
>     'fuzziness' => env('TNTSEARCH_FUZZINESS', false),
>     'fuzzy' => [
>         'prefix_length' => 2,
>         'max_expansions' => 50,
>         'distance' => 2
>     ],
>     'asYouType' => false,
>     'searchBoolean' => env('TNTSEARCH_BOOLEAN', false),
>     'maxDocs' => env('TNTSEARCH_MAX_DOCS', 500),
> ], 

Same these steps.

**Comment by faizan-glowlogix** [comment]
after that i run **php artisan scout:import App\\Models\CarIn** 
![image](https://user-images.githubusercontent.com/66687523/108563926-20214400-7324-11eb-971c-9e856a52bded.png)

**Comment by faizan-glowlogix** [comment]
Following this video https://www.youtube.com/watch?v=yuG1kS9WFz0&t=4s

**Comment by faizan-glowlogix** [comment]
NameSpace

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class CarIn extends Model

```

**Comment by stokic** [comment]
The error says it all, there is no namespace app, there is App...

**Comment by faizan-glowlogix** [comment]
Thanks for the help it is resolved. the problem is with the backslash

`php artisan scout:import App\Models\CarIn` Is is working

`php artisan scout:import App\\Models\\CarIn ` it is not

**Comment by simion-chis** [comment]
You can also use ```php artisan scout:import "App\Models\CarIn"```
