### ISSUE TITLE
could not find driver {"exception":"[object] (PDOException(code: 0):

### ISSUE THREAD

**Issue by michelmelo** [teamtnt/laravel-scout-tntsearch-driver#313]
[2021-03-27 11:12:11] production.ERROR: could not find driver {"exception":"[object] (PDOException(code: 0): could not find driver at /var/www/mysite/vendor/teamtnt/tntsearch/src/TNTSearch.php:82)
[stacktrace]
#0 /var/www/mysite/vendor/teamtnt/tntsearch/src/TNTSearch.php(82): PDO->__construct()
#1 /var/www/mysite/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(155): TeamTNT\\TNTSearch\\TNTSearch->selectIndex()
#2 /var/www/mysite/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(119): TeamTNT\\Scout\\Engines\\TNTSearchEngine->performSearch()
#3 /var/www/mysite/vendor/laravel/scout/src/Builder.php(308): TeamTNT\\Scout\\Engines\\TNTSearchEngine->paginate()

**Comment by nticaric** [comment]
Can you make sure that you have `sqlite` driver installed?

```bash
sudo apt-get install php7.x-sqlite
```

Restart Apache

```bash
sudo service apache2 restart
```

Restart Nginx

```bash
sudo service nginx restart
```

**Comment by michelmelo** [comment]
tks
