### ISSUE TITLE
Use MySQL database instead of Sqlite?

### ISSUE THREAD

**Issue by nivv** [teamtnt/laravel-scout-tntsearch-driver#32]
Is there a way to configure a MySQL database instead of the Sqlite option? My disk has poor IO-performance, and I wanted to try it out using a MySQL db instead.

TNT should support it:
https://github.com/teamtnt/tntsearch#creating-an-index

**Comment by stokic** [comment]
I don't think MySQL as a index source will be added so Sqlite is fast enough and today you can get a server with SSD disk for 5$ per month... :)

What exactly is the issue in your case? Do you have an example on what exactly is slow?

**Comment by nivv** [comment]
@stokic hehe yea, I'm on AWS. Problem is that I need to index 1000+ records every hour or so, and queuing these up takes a long time (15 min). It goes a bit faster if not using the queue.

**Comment by nticaric** [comment]
Can you test the index duration with the command:

`php artisan tntsearch:import App\\Model`

Since everything happens in memory it should be pretty fast

**Comment by nivv** [comment]
@nticaric oh, that took like 2 seconds. Is there a way to disable the automatic indexing after the model has been updated? (I update all of the items on each import run)

**Comment by jdavidbakr** [comment]
Another reason I could see for using MySQL as an index source would be if you have multiple servers behind a load balancer - how would you maintain consistency between each server's index without having a remote database to manage it?

**Comment by nivv** [comment]
For reference, you can easily disable the automatic model observer manually.

```php
Model::disableSearchSyncing();
$model->save()
```

**Comment by nticaric** [comment]
@jdavidbakr a solution to maintain consistency would be to have a shared disk, I think this should be possible to do with aws.

Changing the index source to mysql would remove some features like for example having uuids instead of integers as the primary key. SQLite uses a dynamic typing system while MySQL uses a static one which means you cannot put anything you want into a field.
