### ISSUE TITLE
Everything working fine in heroku console but indexes does not persist.

### ISSUE THREAD

**Issue by 2bona** [teamtnt/laravel-scout-tntsearch-driver#325]
So i have finished the installation and have not had one error, but for some reason the index files does not persist to the storage folder when u close the console. Help please?

**Comment by nticaric** [comment]
You can learn more about your issue [here](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted)

If you have the option, one of the solutions would be to commit the index, so that it gets deployed together with the rest of the app.

**Comment by 2bona** [comment]
Thank you so much, it makes sense now.

**Comment by 2bona** [comment]
Thank you a lot, although the work around is not suitable for my use case.
