### ISSUE TITLE
i have issue in traslate package

### ISSUE THREAD

**Issue by vahidalvandi** [teamtnt/laravel-scout-tntsearch-driver#330]
i need just search in current lang , i use searchable trait in another model with use "astrotomic/laravel-translatable": "^11.5",

```
         $rows = page::whereHas('translations', function ($query) use ($q) {
                $query->search($q);
            })->take(50)->get();

```

it return Call to undefined method Illuminate\Database\Eloquent\Builder::search()

**Comment by stokic** [comment]
ok can you please stop opening double issues in both packages, you've already got the answer.

**Comment by vahidalvandi** [comment]
oh yes , i think mistake in none laravel , then i send in this

**Comment by vahidalvandi** [comment]
i need join to parent table for check is_draft ,...

please help me . database structure is
post
post_trans

serchable trait is in post_trans model and setting is in post tabel

**Comment by stokic** [comment]
this is a laravel/php issue/problem. it has nothing to do with packages. Again, please stop spamming repositories. If you have general questions ask them on [https://stackoverflow.com](https://stackoverflow.com )
