### ISSUE TITLE
Search with relationship(s)

### ISSUE THREAD

**Issue by schubertadam** [teamtnt/laravel-scout-tntsearch-driver#333]
Hi, is there any way to use Model::search method via with() function? I'd like to search through my User model which has Role
This is my original code:
`User::with('roles')->paginate($this->paginate)`

So my question is, how can I make it searchable?

**Comment by danijelMarjanovic** [comment]
Try 
User::search($searchPhrase)->query(function($builder) {
            $builder->with('roles')
        })->paginate($this->paginate)
