### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by mebron** [teamtnt/laravel-scout-tntsearch-driver#34]
Laravel Scout paginate not working when using 'tntsearch'. The pagination working well when using 'algolia' driver.

**Comment by nticaric** [comment]
Can you please try to update both `tntsearch` and `laravel-scout-tntsearch-driver` by doing

```
composer update
```

and then try again. Let us know if it works

**Comment by mebron** [comment]
Now working, thank you
