### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by eshimischi** [teamtnt/laravel-scout-tntsearch-driver#351]
10.0 with support of PHP 8.1 is just released https://github.com/laravel/laravel/releases

**Comment by websitevirtuoso** [comment]
Can you check it please? I hope you have access
@nticaric

**Comment by eshimischi** [comment]
Support is already added, but in dev version ^1.0@dev, so to install it you should have 
`"minimum-stability": "dev",`

**Comment by ultrono** [comment]
> 

Will that work, as Laravel 10 composer file has `stable1 i.e. https://github.com/laravel/laravel/blob/10.x/composer.json#L64

**Comment by eshimischi** [comment]
Here is my project's composer.json (part of it) and it does work until team will make it stable we have to use ^1.0@dev:
`
"require": {
        "php": "^8.1 || ^8.2",
        "ext-json": "*",
        "laravel/framework": "^10.0",
        "teamtnt/laravel-scout-tntsearch-driver": "^1.0@dev"
},
"minimum-stability": "dev",
"prefer-stable": true
`

**Comment by ultrono** [comment]
Right, did this without changing the stability tag within my `composer.json` 🚀 

- `composer remove teamtnt/laravel-scout-tntsearch-driver`
- `composer require teamtnt/laravel-scout-tntsearch-driver:^1.0@dev`

That allowed everything to install under Laravel 10.

I'm a confused as to why the `12.1.0` tag doesn't have the updates from original PR #350, which was merged 3 weeks ago. Assume @nticaric just needs to make a new release? The latest tag shows Laravel 10 support missing, https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/v12.1.0/composer.json. Imagine this will put off and/or confuse a lot of people, as simple `composer require teamtnt/laravel-scout-tntsearch-driver` is expected 😄

**Comment by eshimischi** [comment]
> Right, did this without changing the stability tag within my `composer.json` 🚀
> 
> * `composer remove teamtnt/laravel-scout-tntsearch-driver`
> * `composer require teamtnt/laravel-scout-tntsearch-driver:^1.0@dev`
> 
> That allowed everything to install under Laravel 10.
> 
> I'm a confused as to why the `12.1.0` tag doesn't have the updates from original PR #350, which was merged 3 weeks ago. Assume @nticaric just needs to make a new release? The latest tag shows Laravel 10 support missing, https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/v12.1.0/composer.json. Imagine this will put off and/or confuse a lot of people, as simple `composer require teamtnt/laravel-scout-tntsearch-driver` is expected 😄

when i opened this issue i did see the last commit, but version wasn't being risen perhaps he has more features to add, let's see

**Comment by ultrono** [comment]
Fair enough. The workaround should be fine for the moment. However, I'd expect a project so popular be supporting the latest Laravel releases fairly quickly, especially when  adding support for Laravel 10 is small commit. Agree that they may be preparing a major release.

For none supported packages @laravel-shift kind of saved me, see https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/350#issuecomment-1408784533 :)

**Comment by eshimischi** [comment]
> Fair enough. The workaround should be fine for the moment. However, I'd expect a project so popular be supporting the latest Laravel releases fairly quickly, especially when adding support for Laravel 10 is small commit. Agree that they may be preparing a major release.
> 
> For none supported packages @laravel-shift kind of saved me, see [#350 (comment)](https://github.com/teamtnt/laravel-scout-tntsearch-driver/pull/350#issuecomment-1408784533) :)

There are thousands of unmaintained projects around, even if L is getting an update it doesn't mean every maintainer will adapt their craft package the same second, Rome wasn't built in 3 days, you know..

**Comment by nticaric** [comment]
Here you go, a new release was made :)
