### ISSUE TITLE
Error in TNTSearchScoutServiceProvider@boot

### ISSUE THREAD

**Issue by mostafaznv** [teamtnt/laravel-scout-tntsearch-driver#36]
i installed your package but i get this error when i want to run my application

`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager`

i think the error refer to this line:
`$this->app[EngineManager::class]->extend('tntsearch', function () {`

**Comment by nticaric** [comment]
Have you added `Laravel\Scout\ScoutServiceProvider::class,` to your service provider list?

**Comment by dicarlosystems** [comment]
Had the same issue, nticaric's comment pointed out my oversight!
