### ISSUE TITLE
Relational Search

### ISSUE THREAD

**Issue by naumanahmed19** [teamtnt/laravel-scout-tntsearch-driver#37]
Hi, Thanks for this awesome package. Can you please tell me how to implement something like this
I have 2 tables

 Movies (hasManyActors)
 Actors (belongsToMovies)

now i want to search movies by actor name. I have read on forums that  I may need to use egar load but how to implement this for larvel scout search?

```
Movies::whereHas('actors', function ($q) {
   $q->where('name', 'like', 'abc');
})->with('actors')->get();
```

**Comment by naumanahmed19** [comment]
okay I tried algolia and this worked for me but wondering why its not working with tntsearch
```
	public function toSearchableArray()
	{
		$extra_data = [];
		$extra_data['actors'] = array_map(function ($data) {
			return $data['name'];
		}
		, $this->actors->toArray());
		
		return array_merge($this->toArray(), $extra_data);
	}
```

**Comment by AdrianKuriata** [comment]
Someone did it?

**Comment by blackfyre** [comment]
The problem is that the search driver cannot process array type model attributes, only strings.

**Comment by scottgrayson** [comment]
Would this work?
I'm attempting it now, but having other problems
```
    public function toSearchableArray()
    {
        // there is definitely a cleaner way to do this
        $search = collect($this->toArray())->only([
            'name',
            'email',
        ])->toArray();

        // relevant section for relations
        $search['address'] = isset($this->address)
            ? implode('', $this->address->toSearchableArray())
            : '';

        $search['profile'] = isset($this->profile)
            ? implode('', $this->profile->toSearchableArray())
            : '';

        return $search;
    }
```

**Comment by breadlesscode** [comment]
```php
    public function toSearchableArray()
    {
        $this->project;
        $array = $this->toArray();
        $array['project_name'] = $array['project']['title'];
        unset($array['project']);
        return $array;
    }
```

I tryed this approach but if I search there is no project_name in my result. 

Anyone solved this problem?

**Comment by stokic** [comment]
Did you reindex the data afterwards? If yes, how? 
What data do you have in your index after reindexing?

**Comment by breadlesscode** [comment]
I ran ``php artisan scout:flush App\\Models\\MyModel`` and then ``php artisan scout:import App\\Models\\MyModel``.

I tried ``php artisan tntsearch:import App\\Models\\MyModel`` but this throws: 

```
 [PDOException]                                                           
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'project_name' i  
  n 'field list'                                                           
```

``php artisan scout:import App\\Models\\MyModel`` works  but my result model has no project_name attribute.

Laravel: v5.3.28
laravel-scout-tntsearch-driver: v2.0.1

**Comment by nticaric** [comment]
Your result model won't have an `project_name` attribute since it doesn't exist on your model. It's still fetched as $model->project['title']

**Comment by breadlesscode** [comment]
Thanks! Yes you are right =)
