### ISSUE TITLE
Class InnoDB not found issue.

### ISSUE THREAD

**Issue by sakib3201** [teamtnt/laravel-scout-tntsearch-driver#371]
Getting error called "Class InnoDB not found" after upgrading laravel to 11 and tntsearch to the latest version. 

The issue occurs from the method:

```
public function loadConfig(array $config)
    {
        $this->config            = $config;
        $this->config['storage'] = rtrim($this->config['storage'], '/') . '/';

        // Check if 'engine' key is set in the config
        if (!isset($this->config['engine'])) {
            $this->config['engine'] = \TeamTNT\TNTSearch\Engines\SqliteEngine::class;
        }

        // Create the engine instance based on the config
        $engine       = $this->config['engine'];
        $this->engine = new $engine;   // Error Occurs in this line.

        $this->engine->loadConfig($config);
    }

```
I am using MySql . This issue doesn't appeara if I downgrade the laravel version to 10 and then downgrade tntsearch current version(14.0.0) to the previous(13.x.x) version. Is there a way to resolve this issue?

In my config/database.php the database configuration is set as below:
'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'db_name'),
            'username' => env('DB_USERNAME', 'db_username'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => 'InnoDB',
            'dump' => [
                'dump_binary_path' => '/usr/local/bin', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 5, // 5 minute timeout
                'exclude_tables' => ['table1', 'table2'],
                // 'add_extra_option' => '--optionname=optionvalue',
            ],
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

Here the error log of the problem:
[2024-07-29 11:14:10] production.ERROR: Class "InnoDB" not found {"exception":"[object] (Error(code: 0): Class \"InnoDB\" not found at C:\\xampp\\htdocs\\Incevio\\vendor\\teamtnt\\tntsearch\\src\\TNTSearch.php:42)
[stacktrace]
#0 C:\\xampp\\htdocs\\Incevio\\vendor\\teamtnt\\laravel-scout-tntsearch-driver\\src\\TNTSearchScoutServiceProvider.php(26): TeamTNT\\TNTSearch\\TNTSearch->loadConfig()
#1 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(120): TeamTNT\\Scout\\TNTSearchScoutServiceProvider->TeamTNT\\Scout\\{closure}()
#2 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(100): Illuminate\\Support\\Manager->callCustomCreator()
#3 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php(80): Illuminate\\Support\\Manager->createDriver()
#4 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\scout\\src\\EngineManager.php(30): Illuminate\\Support\\Manager->driver()
#5 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\scout\\src\\Searchable.php(339): Laravel\\Scout\\EngineManager->engine()
#6 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\scout\\src\\Builder.php(518): App\\Models\\Inventory->searchableUsing()
#7 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\scout\\src\\Builder.php(416): Laravel\\Scout\\Builder->engine()
#8 C:\\xampp\\htdocs\\Incevio\\app\\Common\\InventorySearch.php(35): Laravel\\Scout\\Builder->paginate()
#9 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\Storefront\\HomeController->search()
#10 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#11 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#12 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(206): Illuminate\\Routing\\Route->runController()
#13 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(808): Illuminate\\Routing\\Route->run()
#14 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#15 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\XssSanitizer.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\XssSanitizer->handle()
#17 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\CookieConsentMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\CookieConsentMiddleware->handle()
#19 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\Storefront.php(83): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\Storefront->handle()
#21 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\Language.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\Language->handle()
#23 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\InitSettings.php(92): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\InitSettings->handle()
#25 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#40 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(750): Illuminate\\Routing\\Router->runRoute()
#42 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#43 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#44 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 C:\\xampp\\htdocs\\Incevio\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#47 C:\\xampp\\htdocs\\Incevio\\app\\Http\\Middleware\\CheckForInstallation.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): App\\Http\\Middleware\\CheckForInstallation->handle()
#49 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#52 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#55 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#57 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#59 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#61 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#63 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#65 C:\\xampp\\htdocs\\Incevio\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#66 C:\\xampp\\htdocs\\Incevio\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#67 C:\\xampp\\htdocs\\Incevio\\server.php(21): require_once('...')
#68 {main}
"}

**Comment by nticaric** [comment]
Try to remove this line `'engine' => 'InnoDB',` from your config and see if it works

**Comment by sakib3201** [comment]
> Try to remove this line `'engine' => 'InnoDB',` from your config and see if it works

Thank you so far my issue has been fixed. This doesnt seem to be mentioned anywhere. Is there a particular reason why this issue occured? It didnt cause any issue for the previous versions.

**Comment by sakib3201** [comment]
Closing the issue since the problem has been solved.
