### ISSUE TITLE
Undefined var username when testing against an sqlite database

### ISSUE THREAD

**Issue by talv86** [teamtnt/laravel-scout-tntsearch-driver#4]
I'm trying to run unit tests against an sqlite database in memory with the following credentials:

```
[
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
            'strict'   => false,
]
```

However when I run them i get the following error:

```
ErrorException: Undefined variable: username in /home/talv/Projects/easel/vendor/teamtnt/tntsearch/src/Connectors/Connector.php:46
```
The problem arises from the extract  function not having a `$username` and `$password` keys to extract:
```
    public function createConnection($dsn, array $config, array $options)
    {
        extract($config, EXTR_SKIP);

        return new PDO($dsn, $username, $password, $options);

    }
```

I then created 2 null values within my database connection for username and password and it got passed the connector part however it brings the following errors

````
PDOException: SQLSTATE[HY000]: General error: 1 no such table: posts in /home/talv/Projects/easel/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:173
Stack trace:
#0 /home/talv/Projects/easel/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(173): PDO->query('SELECT id, titl...')
#1 /home/talv/Projects/easel/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(167): TeamTNT\TNTSearch\Indexer\TNTIndexer->run()
#2 /home/talv/Projects/easel/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(33): TeamTNT\Scout\Engines\TNTSearchEngine->initIndex(Object(Easel\Models\Post))
#3 /home/talv/Projects/easel/vendor/laravel/scout/src/Searchable.php(41): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection))
#4 /home/talv/Projects/easel/vendor/laravel/scout/src/Searchable.php(24): Easel\Models\Tag->queueMakeSearchable(Object(Illuminate\Database\Eloquent\Collection))
#5 [internal function]: Illuminate\Database\Eloquent\Collection->Laravel\Scout\{closure}()
#6 /home/talv/Projects/easel/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(78): call_user_func_array(Object(Closure), Array)
#7 /home/talv/Projects/easel/vendor/laravel/scout/src/Searchable.php(87): Illuminate\Support\Collection->__call('searchable', Array)
#8 /home/talv/Projects/easel/vendor/laravel/scout/src/ModelObserver.php(61): Easel\Models\Post->searchable()
#9 [internal function]: Laravel\Scout\ModelObserver->created(Object(Easel\Models\Post))
.....
```

It seems thats the migrations to create the tables break with the introduction of username and password keys for the sqlite databases in memory. 

Any ideas on how to fix the above?

Removing the tests for searching and the username and password keys allows all my tests to work as normal.

**Comment by nticaric** [comment]
@talv86 Thanks for taking the time to look into this issue. I am aware of this, but to be honest, don't know how to deal with it. The problem here is the in memory sqlite database. 
Let me try to explain.

In order to be able to create an index, you need a database with some tables to index. In your case, this is the `posts` table. Naturally, to run the phpunit tests fast, you create an in memory sqlite database and run the migrations. So far, so good. Now, you want `TNTSearch` to connect to the same in memory database and you again define a :memory: connection, but this time in TNTSearch. The problem is that every :memory: database is distinct from every other which means that they don't share the `posts` table that you just created with your migration. So, opening two database connections each with the database name ":memory:" will create two independent in-memory databases.

Setting the database name as `file::memory:?cache=shared` doesn't seem to do the trick with PDO. So I am kinda out of solutions. If someone else knows how to share the in memory database it would be much appreciated.

**Comment by talv86** [comment]
Ahh i see! Thanks for the explanation of whats going on. I totally understand why theyre failing now, however can you recommend an alternative way to unit test when using using TNTSearch?

**Comment by nticaric** [comment]
I managed to solve this issue by sharing laravels connection with TNTSearch. So if you checkout
version `v1.0.2` of laravel-scout-tntsearch-driver it should work fine. Let me know

**Comment by talv86** [comment]
Awesome! Great work! Although when I'm running my tests now I'm getting the following error:

```
[2016-08-20 18:21:01] testing.ERROR: TeamTNT\TNTSearch\Exceptions\IndexNotFoundException: Index /home/talv/Projects/easel/vendor/orchestra/testbench/src/Traits/../../fixture/storage/tags.index does not exist in /home/talv/Projects/easel/vendor/teamtnt/tntsearch/src/TNTSearch.php:65
Stack trace:
#0 /home/talv/Projects/easel/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(102): TeamTNT\TNTSearch\TNTSearch->selectIndex('tags.index')
#1 /home/talv/Projects/easel/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(73): TeamTNT\Scout\Engines\TNTSearchEngine->performSearch(Object(Laravel\Scout\Builder))
#2 /home/talv/Projects/easel/vendor/laravel/scout/src/Engines/Engine.php(62): TeamTNT\Scout\Engines\TNTSearchEngine->search(Object(Laravel\Scout\Builder))
#3 /home/talv/Projects/easel/vendor/laravel/scout/src/Builder.php(115): Laravel\Scout\Engines\Engine->get(Object(Laravel\Scout\Builder))
#4 /home/talv/Projects/easel/src/Http/Controllers/Backend/SearchController.php(23): Laravel\Scout\Builder->get()
#5 [internal function]: Easel\Http\Controllers\Backend\SearchController->index()
```

I'm calling the `scout:import` command in my setup method of the class running the tests:

```
    public function setUp()
    {
        parent::setUp();
        
        \Artisan::call('scout:import', ['model' => '\\Easel\\Models\\Post']);
        \Artisan::call('scout:import', ['model' => '\\Easel\\Models\\Tag']);
    }
```
In this instance I can see the physical file `posts.index` being created but no idea why the `tags.index` isn't being generated.

Any ideas?

**Comment by nticaric** [comment]
Can you try with the latest version of the package?
