### ISSUE TITLE
write a readonly database

### ISSUE THREAD

**Issue by romeox6x66** [teamtnt/laravel-scout-tntsearch-driver#45]
i got this error ,

[PDOException]
  SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

**Comment by stokic** [comment]
it's probably not related to the package... but it seems like you have a readonly index/sqlite file, make it writeable and it'll work...

**Comment by romeox6x66** [comment]
this error coming with file name is TNTIndexer

**Comment by stokic** [comment]
Yes, and it's a PDOException, it doesn't matter where it comes from, PDO says that it's can't write to the database and TNTSearch package uses sqlite database for indexes as explained in the readme...
https://github.com/teamtnt/tntsearch/blob/master/README.md#creating-an-index

Check your search index file as suggested, there is a permission problem as the error says...

**Comment by gideon-maina** [comment]
If you're using the apache2 or nginx web servers , make sure the user running the processes has write access to the sqlite files (indexes) you generated.
