### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by denisrpriebe** [teamtnt/laravel-scout-tntsearch-driver#47]
I have a form where a user starts typing the name of a product. As they type, the string is sent via ajax to a ProductController which basically does the the following:

`$products = Product::search($value)->take(8)->get();`

However, while the user is typing I get the following error:

![capture](https://cloud.githubusercontent.com/assets/8739001/20313002/1a9b37be-ab1b-11e6-994e-0796d44da640.JPG)

This only happens when the part of the product name is typed. Once the user types the full product name everything works.

This error occurs on my local setup only. I deployed my application to forge and everything works flawlessly. Is there some setting I need to change in my php.ini file?

**Comment by stokic** [comment]
Hm from what you've wrote I would guess that you have the same index on the live and local server, but on the local server you don't have item with id 21... if so then just reindex everything on your local server and that's it :)

Read this quickly on my phone so maybe I've missed something

**Comment by denisrpriebe** [comment]
@stokic Thanks for the response. The index that gets generated by scout/tntsearch-driver is in my .gitignore file and so isn't committed to version control. Hence, when i publish code to forge the index gets rebuilt the same way as it would on my local setup. Also I have less than 5 products in my database table which none of them have an id that goes to 21. Ids are 1 - 5.

**Comment by nticaric** [comment]
Whats happens alter you reindex locally?

**Comment by denisrpriebe** [comment]
@nticaric I ran the command

`php artisan scout:import App\\Models\\Product`

The result was:

`Imported [App\Models\Product] models up to ID: 5`
'All [App\Models\Product] records have been imported.'

**Comment by nticaric** [comment]
And you are still getting the same error?

**Comment by denisrpriebe** [comment]
@nticaric Yes.

**Comment by denisrpriebe** [comment]
@nticaric @stokic The error does change depending on what the user searches for. For 
![capture](https://cloud.githubusercontent.com/assets/8739001/20314962/bbe8bfd2-ab21-11e6-8f13-4bb8f8e17f54.JPG)
example the user might search by the price of the product or the category the product is in.

Notice the Undefined offset is now 45 rather than 21 like in my original post.

**Comment by nticaric** [comment]
Based on your description, at some point in time you had the missing index 45, 21 etc. in your database. After you deleted them, they still stayed in the index. The command 'php artisan scout:import Model' will insert new records to the index but also keep the old one since its basically an 'update' call. What you need to do is manually remove the index from your storage folder.

**Comment by denisrpriebe** [comment]
@nticaric You're right. I deleted the index completely and re-generated it with `php artisan scout:import` and that seems to have solved the issue. Thank you very much for your help. Tntsearch-driver is an awesome package!
