### ISSUE TITLE
$asYouType option in config/scout.php

### ISSUE THREAD

**Issue by jdfx** [teamtnt/laravel-scout-tntsearch-driver#49]
Hi guys

Great package. I couldn't find any documentation surrounding 'as you type' or quite how to use it in conjunction with the package. For now I have hardcoded it to true in vendor which is certainly wrong.

Should this be a config option? Or is there a way to use it on a per search basis i.e. 

$result = App\Stuff::search($keyword)->asYouType()->get();

Apologies if I have missed something obvious, I did Google for quite some time.

**Comment by newpain01** [comment]
It would be nice if we can get some more info in the readme for the other properties as well, for example how to define which columns should be searchable or description about the fuzzy properties.

**Comment by jdfx** [comment]
Agreed, the fuzzy property definitions I had to work out from the Elastic Search documentation.

**Comment by newpain01** [comment]
Me too, I read the Elastic Search documentation, but I am still not sure if I configured it correctly. And I still can't figure out how to define which columns to use with toSearchableArray().
I am willing to help update the docs and contribute to the project, but need a little help from the owner.

**Comment by stokic** [comment]
If I remember correctly asYouType isn't available through configuration but it could be in the next update, what do you think @nticaric ?

As far as the toSearchableArray() goes that's part of the Laravel Scout, not this driver specifically so you should check Laravel's docs, unfortunately you wont find anything there so to keep it short, you just have to return array from that method ie.

```
return [ 'title' => $this->title, 'content' => $this->content]
```

**Comment by newpain01** [comment]
@stokic Thanks a lot for your answer, this is very helpful. What about the fuzzy property, can you point at some direction where to find more info?
Here is my scenario:
I am searching in a notes table where I have 'topic' and 'content' fields and for example my note topic is 'qwe'. (I defined toSearchableArray() to only index topic and content) When I search for 'qwe' it will return my note (I only have one), but when I search for 'qw' it will return my note as 4-5th note, but the previous notes don't even contain 'qw'. Am I missing some configuration?
