### ISSUE TITLE
Error when import table

### ISSUE THREAD

**Issue by mostafaznv** [teamtnt/laravel-scout-tntsearch-driver#50]
when i want to import a table, i get this error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class TeamTNT\Scout\Engines\TNTSearchEngine contains 1 abstract method and must therefore be declared abst
  ract or implement the remaining methods (Laravel\Scout\Engines\Engine::mapIds)
```

**Comment by ReinforcedPanda** [comment]
I too am getting this error
`[Symfony\Component\Debug\Exception\FatalErrorException]
  Class TeamTNT\Scout\Engines\TNTSearchEngine contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Scout\Engines\Engine::mapIds)
`

**Comment by jaydeluca** [comment]
I had the same issue, and then i updated to the dev master branch, and used "php artisan tntsearch:import "App\ModelName" instead, and all is working now
