### ISSUE TITLE
Error when trying to search

### ISSUE THREAD

**Issue by slickorange** [teamtnt/laravel-scout-tntsearch-driver#51]
I get the following error when trying to do Model::search('query')->get():

`"TNTSearchEngine contains 1 abstract method and must therefore be declared abstract or implement the remaining methods"`

I am using Laravel 5.3. (Using https://github.com/codecasts/spa-starter-kit)
I have installed Scout as indicated in the Laravel documentation.

Any ideas what could be causing this?

**Comment by stokic** [comment]
Did you do all of the steps of installation as indicated at https://github.com/teamtnt/laravel-scout-tntsearch-driver#installation ?

**Comment by slickorange** [comment]
Yes.

Seems like the following code was added to Laravel Scout 3 days ago, I think that is causing the issue.. (https://github.com/laravel/scout/commit/aff5172ba7be3562e81f71999534a7a8046bb813)

` /**
 +     * Pluck and return the primary keys of the given results.
 +     *
 +     * @param  mixed  $results
 +     * @return \Illuminate\Support\Collection
 +     */
 +    abstract public function mapIds($results);
 +
 +    /**`

**Comment by salahy** [comment]
I got the same error, did you fix it ?

**Comment by stokic** [comment]
Please update the package and try again

**Comment by mostafaznv** [comment]
thanks for fix
