### ISSUE TITLE
Usage with Laravel Scout v2.*

### ISSUE THREAD

**Issue by austintoddj** [teamtnt/laravel-scout-tntsearch-driver#53]
Getting this error in [Canvas](https://github.com/cnvs/canvas) when updating Laravel Scout to `v2.*`. Any thoughts or possibility of adding support for this?

![screen shot 2016-12-20 at 3 25 33 pm](https://cloud.githubusercontent.com/assets/8037011/21368526/9360f8c8-c6c8-11e6-82bc-07a8fffccbc4.png)

**Comment by nticaric** [comment]
Can you try with the dev-master version of `laravel-scout-tntsearch-driver`, it's implemented there

**Comment by austintoddj** [comment]
I'll give that a shot shortly.

**Comment by austintoddj** [comment]
The error still exists when using dev-master.

**Comment by austintoddj** [comment]
Resolved with commit: f09864154d4441576fabd4c7a0c440a6ffa3dfcd
