### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getTablePrefix()

### ISSUE THREAD

**Issue by austintoddj** [teamtnt/laravel-scout-tntsearch-driver#54]
Integrating TNTSearch with [Easel](https://github.com/cnvs/easel) has hit a bug on line 199 of `src/TNTSearchScoutServiceProvider.php`.

Any assistance on the solution would be great! 👍 

If you want to replicate the error, go ahead and follow these steps:

- `git clone https://github.com/cnvs/canvas.git`
- `git checkout develop`
- `cp .env.example .env`
- `composer install`
- `php artisan canvas:install`

**Comment by nticaric** [comment]
@austintoddj Ok, I think it should be fixed now. Try with version 2.0 https://github.com/teamtnt/laravel-scout-tntsearch-driver/releases/tag/v2.0.0

Also, I noticed that in the setup process of canvas the tags.index isn't created, so when doing a search for the first time it will throw an error, so it would be good to add the index during the setup process together with posts.

**Comment by austintoddj** [comment]
The newest version you released works like a charm @nticaric! Thanks for the rapid feedback and the bug fix. 🍻
