### ISSUE TITLE
Where and order by conditons aren't changing result set

### ISSUE THREAD

**Issue by sergiocastrovale** [teamtnt/laravel-scout-tntsearch-driver#59]
None of these queries seems to have any effect on the result set of my Ads model:

```
Ad::search($query)->where('type_id', $type)->get();
```

```
Ad::search($query)->orderBy('created_at', 'desc')->get();
```

Am I doing something wrong or is this something tntsearch driver doesn't support yet?

**Comment by stokic** [comment]
It doesn't as far as I know :)

Although simple where might be useful in some cases and probably will be supported soon, I'm not sure orderBy makes sense in full text search, where implied order is by query result relevance... 

@nticaric what do you think?

**Comment by sergiocastrovale** [comment]
Picture my scenario ... I want to list ads from a specific type (I can go around it by merging the type within the query) but I want the most recent to appear first. So, It would be something like:

```
Ad::search($query)->where('type_id', $type)->orderBy('created_at', 'asc')->get();
```

As we don't have where() as of now, I can search for something like 'an_add_title a_type_name' and deal with the query separately, but I don't have any idea on how to order that result set. Any ideas?

**Comment by stokic** [comment]
Ok, what is the reason you are doing full text search in the first place? I'm guessing you are using it as a bit better "LIKE" operator but the actually relevance is not that important...? :)

In current situation you could either create separate indexes for each type or do filtering on the results ie. you fetch all that the search returns and then filter on the collection in php (both have their drawbacks)

**Comment by sergiocastrovale** [comment]
Having the ability for fuzzy searching and weighting relevance is important, but I see your point it how it is conflicting with ordering ... I think I'm going to sort the list afterwards since I'm working with VueJS. It will probably make things easier in the long run.
