### ISSUE TITLE
[Suggestion] asYouType runtime option

### ISSUE THREAD

**Issue by LasseRafn** [teamtnt/laravel-scout-tntsearch-driver#60]
Would it make sense to have an option to enable/disable asYouType runtime? Like, if your app would need both. At least I have different places on my page, that searches differently:
- some that shows results beneath; autocompletion/typeahead-ish
- and one that only returns on ENTER (hence no need for asYouType)

I'd gladly spend some time looking into a solution and create a PR.

**Comment by nticaric** [comment]
Ok, let's see how people are reacting to this. If it's in demand I guess we should add it. Another option is to use the TNTSearch package directly without the scout driver to query the index.

**Comment by BirdyUK** [comment]
@nticaric - My idea is to use this package with scout for Address autocompletion similar to how google works when you start typing an address it will find the relative ones and display them in a drop down.

I have the data that is over 30+ million.. I have imported 10 million so far and waiting for the other 20 to finish as we speak to run tests against an optimized sql database.

If this works out i will certainly be donating some funds via the Backer service.

What's your thoughts, You think this is possible and would run smoothly?

**Comment by nticaric** [comment]
In version v2.0.5 this has been added as a runtime option

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use Searchable;
    public $asYouType = true;
    
}
```
