### ISSUE TITLE
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected?

### ISSUE THREAD

**Issue by vipin733** [teamtnt/laravel-scout-tntsearch-driver#62]
I try to use laravel scout in my app its giving errors when i hit the submit button.But when I use tinker its giving me result I changed in TNTSearch.php line 67 sqlite to mysql. Then its giving errors.
Any help
Thanks

**Comment by nticaric** [comment]
Try to follow this tutorial step by step 

https://laravel-news.com/tntsearch-with-laravel-scout

**Comment by vipin733** [comment]
I follow the same step but its happended

**Comment by nticaric** [comment]
Firstly, you shouldn't change anything in TNTSearch.php on line 67, because sqlite is for the index not for your database. In order to be able to help you, paste some errors that you're getting and be more verbose

**Comment by vipin733** [comment]
PDOException in TNTSearch.php line 67:
could not find driver

**Comment by nticaric** [comment]
Can you run `phpinfo()` and search for pdo_sqlite?

**Comment by vipin733** [comment]
PDO drivers	mysql

**Comment by nticaric** [comment]
Ok, if you cannot find pdo_sqlite it means that you don't have the sqlite extension installed on your system which is a requirement.

If you're on ubuntu you can install the missing extension with:

`sudo apt-get install php7.0-sqlite3`

and then restarting you're apache/nginx server

**Comment by vipin733** [comment]
actually i'm using window using laragon

**Comment by vipin733** [comment]
thanks I solved it

**Comment by nticaric** [comment]
Great, would be good to share your solution here so that others who stumble upon a same issue know how to solve it.

**Comment by vipin733** [comment]
I just downloded sqlite3 from https://sqlite.org/download.html and after extracting zip file simply i past sqlite.ddl file in php/bin folder and i restart my server its working fine

**Comment by nticaric** [comment]
Thanks
