### ISSUE TITLE
Return specific columns

### ISSUE THREAD

**Issue by oliviertam** [teamtnt/laravel-scout-tntsearch-driver#64]
Hello, i want to make this query:

$persons = Person::search($search_value)->get(['id', 'first_name]);

Can anyone tell me if this is possible?

**Comment by simpledev** [comment]
Hi,

`$persons = Person::search($search_value)->pluck('id','name);` ?
return a collection, so add ->toArray() method at the end if you want an array :)

**Comment by TGISolutions** [comment]
I've done this…

        $companies = Company::search($searchString)->get();
        $companyids = array();
        foreach ($companies as $company) {
            $companyids[] = $company->id;
        }

I'm sure there is a better way but it works

**Comment by chribell** [comment]
For anyone still interested, you can pass a callback function to the Scout Builder instance.
```php
    $columns = ['id', 'name'];
    Person::search($searchString)->query(function($query) use ($columns) { 
       $query->select($columns);  
    })->get();
```
