### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by divdax** [teamtnt/laravel-scout-tntsearch-driver#65]
Please support v5.4
```
$app->share()
```
is now
```
$app->singleton()
```

**Comment by nticaric** [comment]
@divdax can you point in code where this needs to be changed?

**Comment by Harti** [comment]
I couldn't find it either. Is this library compatible with 5.4, did anyone check this yet?

**Comment by nticaric** [comment]
Yes it is
