### ISSUE TITLE
Search part of words (LIKE %something%) ?

### ISSUE THREAD

**Issue by navihtot** [teamtnt/laravel-scout-tntsearch-driver#66]
Hi, 
First of all thanks a lot for your work, really love tntsearch and especially nice and easy laravel integration.

Is it possible to do in the middle of word search like classic sql LIKE '%something%'?
As I plan to use it for autocomplete, would really like to give users some results when they omit the first letter of word or similar.
Other thing is if for example if I search for "kind" it will find results with "kind" but not for e.g. "kinder", is there any setting to make it return also words that just begin with search term?
Also its working nicely on my local system but I'm a bit worried about live performance when I get many hits to api and when my db grows (currently I have around 45000 records) - is there any performance benchmark data or something similar available?

**Comment by stokic** [comment]
You can enable fuzzy search, that would enable the results you want/need.

We are planning on doing a benchmark soon, but in general search is very fast even if there are millions of rows, indexing is a bit slow initially with very large number of rows but that's only the initial index, afterwards it should be really fast.

What kind of api are you running if it's not a secret? :)

**Comment by navihtot** [comment]
Hmm I did enable fuzzy search and then it works for e.g. if I do a misspelled word search e.g. "somehting" instead of "something" but still it doesn't find anything if I search for "omething".

maybe I missing something, here is my config:

```php
'tntsearch' => [
	    'storage'  => storage_path('/index'),
	    'asYouType' => true,
	    'fuzziness' => env('SCOUT_TNT_FUZZINESS', true),
	    'fuzzy' => [
	        'prefix_length' => 5,
	        'max_expansions' => 50,
	        'distance' => 2
	    ],
	]
```
And my search query:
```php
$contractees = Contractee::search(Input::get('name'))->get();
```

I'm building autocomplete api for potential clients, it will be called via javascript to autocomplete what user inputs.

**Comment by navihtot** [comment]
Is it also possible to have additional where query (on other non TNTSerch indexed field) ?

**Comment by raphaelbeckmann** [comment]
@navihtot is correct. For example the user "raphael" won't be found if the user typed "raph".

**Comment by raphaelbeckmann** [comment]
How can we find a workaround for this?

**Comment by nticaric** [comment]
@raphaelbeckmann the workaround is to built an index with n-grams, you can read more about it here http://tnt.studio/blog/did-you-mean-functionality-with-laravel-scout

**Comment by michaelklopf** [comment]
To make it work you have to add this to your model class:

`use TeamTNT\TNTSearch\Indexer\TNTIndexer;`

and to your `public function toSearchableArray()` method add:

```php
  $array = $this->toArray();

  $array['nameNgrams'] = utf8_encode((new TNTIndexer)->buildTrigrams($this->name));

  return $array;
```

Worked for me.

**Comment by bleuscyther** [comment]
You can do one array index per field, it will work.!

**Comment by Tofandel** [comment]
That's not a viable workaround in the case of fields with text, eg a long description, building trigrams for each word in the set would require insane amounts of memory, disk space and cpu

That's really a shame that such basic functionnality is not a config option. It's not much of a search engine without that
