### ISSUE TITLE
Exclude model instances from being indexed ?

### ISSUE THREAD

**Issue by MikeMnD** [teamtnt/laravel-scout-tntsearch-driver#67]
$indexer->query("SELECT $query FROM {$model->getTable()};");

With this in the ImportCommand hwo can we customize and pass model scopes?

I don't need search index for all draft, not visible and soft deleted records.
But at the moment it index everything, and i need to make a second index update removing the indexes that shouldn't be there in a first place.

**Comment by fastmover** [comment]
Is this possible?

**Comment by nticaric** [comment]
You can write your own command for creating the index. In this case the query would look something like this:

`$indexer->query("SELECT * FROM table where draft = 0");`
