### ISSUE TITLE
Undefined Offset (intermittent)

### ISSUE THREAD

**Issue by austintoddj** [teamtnt/laravel-scout-tntsearch-driver#68]
While using this package in [Canvas](https://github.com/cnvs/canvas), I'm finding that the search function intermittently throws an undefined offset error. Can't find any consistency with the errors, but have just run into it many times. An example looks like this:

<img width="992" alt="screen shot 2017-02-24 at 1 09 31 pm" src="https://cloud.githubusercontent.com/assets/8037011/23317148/c6e78736-fa92-11e6-873b-f5656c00847c.png">

If you want to try and reproduce the error, try a [quick installation of Canvas](https://cnvs.readme.io/docs) and then sign into the app, and utilize the search function in the top navigation bar.

**Comment by nticaric** [comment]
This would mean that the post's table isn't in sync with the index. The index still thinks that the post with ID 31 exist, but it seems it doesn't. Deleting the index and then doing `php artisan scout:import "App\Post"` would solve the problem, but the question is how it got out of sync? Did you manually delete some posts from the db?

**Comment by austintoddj** [comment]
Hm ok that makes sense. No I don't think any manual deleting was going on in the database, so I'll just have to find out where something could have disrupted the sync. I'll post an answer here as soon as I find it..

**Comment by nticaric** [comment]
Do you also delete the index file each time you test a new iteration of canvas? It could be that the index stayed the same, containing ids from a previous installation

**Comment by austintoddj** [comment]
Ah, I see it now. It was totally a mistake on my part. Along the way of developing the app, we changed the index names from posts.index to canvas_posts.index. The removal and rebuilding of the index was actually never doing anything since it was looking for the wrong files. Thanks for your help @nticaric!
