### ISSUE TITLE
Driver upgrade to Laravel 5.4

### ISSUE THREAD

**Issue by laurovalente** [teamtnt/laravel-scout-tntsearch-driver#70]
Hi,

In order to use the driver in Laravel 5.4, a change is needed into TNTSearchServiceProvider.

The method share was extinct.

So, my suggestion is to change the share method line, by this one:

`        $this->app->singleton('tntsearch',function ($app) {` 

It works.

**Comment by nticaric** [comment]
The scout driver works with Laravel 5.4
