### ISSUE TITLE
Recommend storing indexes in git?

### ISSUE THREAD

**Issue by simonyoti** [teamtnt/laravel-scout-tntsearch-driver#71]
Firstly, thanks for providing this driver and saving me a lot of time writing it myself!

Do you recommend storing the indexes in git or generating them on each platform you pull your repo from?

Thanks

**Comment by stokic** [comment]
Although it might seem convenient I would advise against putting your indexed in git, there are three reasons why. 

First, they can get big, which means your repo will get bigger which in turns makes it slower.
Second, you might have sensitive data, like names, phone numbers, emails etc... in your index, storing that on Github or other service is a security risk.
Third, you will probably have different data set on different machines/environments so your local env for example might overwrite production index which is bad...

But that's just my opinion ;)

**Comment by nticaric** [comment]
Same here, don't put your index into version control
