### ISSUE TITLE
Some issues along the way of installing tntsearch with fixes

### ISSUE THREAD

**Issue by anasred** [teamtnt/laravel-scout-tntsearch-driver#72]
if you run this command
```
php artisan scout:import "App\Contact"
```
and you encounter this error 
```
[ErrorException]                      
Trying to get property of non-object
```
Then it might be related to your model scope function, So disable it and then run the command again.

Or if you encounter something like 
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Class 'AlgoliaSearch\Version' not found  
```
then clear config cache like so, and then run the command again
```
php artisan config:clear
```

I hope these will help someone

btw, i'm using Laravel 5.4

**Comment by swapnilsarwe** [comment]
I have laravel 5.4 installed with `"teamtnt/laravel-scout-tntsearch-driver": "^2.0"` installed and got this error
```
[Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illum
  inate\Support\Manager
```

just added `Laravel\Scout\ScoutServiceProvider::class,` above `TeamTNT\Scout\TNTSearchScoutServiceProvider::class,` as follows
```
Laravel\Scout\ScoutServiceProvider::class,
TeamTNT\Scout\TNTSearchScoutServiceProvider::class,
```

i hope these will help someone and would like to know the explanation if anyone can help with it.

**Comment by nticaric** [comment]
@swapnilsarwe the explanation is simple, TNTSearch extends Scout which means that scout needs to be loaded before TNTSearch

**Comment by nticaric** [comment]
The readme has been updated to reflect some of those errors
