### ISSUE TITLE
Relation search

### ISSUE THREAD

**Issue by pwnz22** [teamtnt/laravel-scout-tntsearch-driver#73]
Hi all!

I need help to search in models hasMany relation,
something like:
`$model->companies->search('Company name')->get();`

My model relation looks like this;
```
public function companies() {
    return $this->hasMany(Company::class);
}
```

Thanks!

**Comment by levonmanucharian** [comment]
Same question! Would really appreciate an answer!

**Comment by reals79** [comment]
Hi,
$results = $model->companies->search('Company name')->get()
                ->load('companies');

In the "load", you can list several relationships (example: ->load('companies', 'addresses', etc...)).

**Comment by pwnz22** [comment]
`$city = \App\City::first();`

When i do `$companies = $city->companies->search('company name');` in `dd($companies);` i'm getting `false `(`boolean`)

**Comment by the94air** [comment]
I am using this in the Model and it is working in one to many relationship (Helpers table and Categories table)

```php
	/**
	* Get the indexable data array for the model.
	*
	* @return array
	*/
    public function toSearchableArray()
    {
      return [
      		'id' => $this->id,
			'title' => $this->title,
			'content' => $this->content,
			'code' => $this->code,
			'category' => $this->category['name'],
      ];
    }

	public function Category()
	{
	    return $this->belongsTo('App\Category');
	}
```
This should be helpful https://laracasts.com/discuss/channels/laravel/scout-how-to-search-in-relations-and-counts/replies/329201

**Comment by pwnz22** [comment]
But i have `hasMany() `relation :(, this approach not working on hasmany relations.

**Comment by the94air** [comment]
I think scout is don't fully support relationship searchs. We may need to wait a title bit.

**Comment by mikebronner** [comment]
The work-around for HasMany relationships is clunky, and may prove to be a performance issue if you have thousands of search results.

Instead of `$blog->posts()->search('...')->get();`, I do the search, then filter by blog ID:
```php
    $posts = (new Post)->search(request('searchText'))->get();
    $posts = $posts->filter(function ($post) use ($blog) {
        return $post->blog_id === $blog->id;
    });
```

**Comment by Alive2212** [comment]
Hi 
I'm sure this way not the best way for resolve this problem and i think Taylor and his team must be resolve them but i resolve it with another way:

**Comment by Alive2212** [comment]
Hi
I'm sure this way not the best way for resolve this problem and i think Taylor and his team must be resolve it issue but i resolve it with another way:
i have a User model and any user have many Device so in user model i have this method

`public function devices()
    {
        return $this->hasMany(Device::class);
    }`
 
first i defined some variable as below

`
    protected $searchableColumns = [
        'name',
        'family',
    ];
    protected $searchableInnerColumns = [
        'devices' => 'imei',
    ];
`

then i wrote "toSearchableArray" as following:

'
    public function toSearchableArray()
    {
        $result = [];
        if (!sizeof($this->searchableColumns)) {
            $result = collect($this);
        } else {
            $result = collect([
                'id' => $this['id'],
            ]);
            foreach ($this->searchableColumns as $searchableColumn) {
                $result->put($searchableColumn, $this[$searchableColumn]);
            }
        }
        if (sizeof($this->searchableInnerColumns)) {
            foreach ($this->searchableInnerColumns as $searchableInnerColumnKey => $searchableInnerColumnValue) {
                $values = $this->{$searchableInnerColumnKey}()
                    ->select($searchableInnerColumnValue)
                    ->get()
                    ->toArray();
                $counter = 0;
                foreach ($values as $value){
                    $result->put($searchableInnerColumnKey . '-' . $searchableInnerColumnValue.'-'.$counter,
                        $value);
                    $counter++;
                }
            }
        }
        return $result->toArray();
    }
'

and result in post man like this:

'{
    "id": 3,
    "name": "Jed Purdy",
    "family": "Upton",
    "devices-imei-0": {
        "imei": "79663"
    },
    "devices-imei-1": {
        "imei": "99958"
    }
}'

**Comment by tranghaviet** [comment]
My solution (if you want to search company name):
In Model:
```
public function toSearchableArray()
{
        $a = $this->toArray();
        $companies = $this->companies()->get(['name'])->map( function ($company) {
                  return $company['name'];
         });
         $a['companies'] = implode(' ', $companies->toArray());
         return $a
}
```
run 'php artisan scout:import App\\ModelName` (use tntsearch:import won't work);

**Comment by the94air** [comment]
That looks awesome. Thanks for sharing the solution with us.

**Comment by zymawy** [comment]
My Solution What I Just Did Is Make The Model That Has Relationships  I Also Made It Searchable And Imported (Indexed )

So I Just Qeury It As Usually  

`$categories = Category::search($request->q)->get();`

This Is Work Fine

**Comment by rico** [comment]
@tranghaviet works great - thanks! You can make this shorter using the `collection->implode`  method:
  
    public function toSearchableArray()
    {

        return [
            'id'       => $this->id,
            'products' => $this->products()
                ->get(['name'])
                ->implode('name', ' ')
        ];
    }

... or even `'products' => $this->products->implode('name', ' ')` for _"light"_ models.

**Comment by akkhan20** [comment]
@tranghaviet what if child row updates? how is that synced to the index??

**Comment by Ssy3** [comment]
@akkhan20
If you find the answer, let us know..

**Comment by davehowson** [comment]
@Ssy3 updating child model does not update the parent when you use it like this. Instead, you should manually update the index by calling the searchable method on the relationship

**Comment by x3mart** [comment]
> @tranghaviet what if child row updates? how is that synced to the index??

use touches
