### ISSUE TITLE
Demo source code

### ISSUE THREAD

**Issue by levonmanucharian** [teamtnt/laravel-scout-tntsearch-driver#75]
Sorry if this is the wrong place to post it, I am trying to replicate what you have in your demo website at http://tntsearch.tntstudio.us. Any chance you could provide the source codes? Thanks so much!

**Comment by nticaric** [comment]
Here it is

https://github.com/teamtnt/tntsearch-demo

It's built with an older release of TNTSearch but the concept is the same.
