### ISSUE TITLE
Driver [tntsearch] not supported in laravel 5.4

### ISSUE THREAD

**Issue by cawhite78** [teamtnt/laravel-scout-tntsearch-driver#76]
php artisan scout:import "App\Location" is giving me this error

--
My apologies about this one.  I see now that it is quite obvious from the README/Git landing page that this is only supported in laravel 5.3

**Comment by getupkid** [comment]
It works in 5.4 for me ... you didn't paste the error, what is it?

**Comment by nticaric** [comment]
Don't forget to add  `TeamTNT\Scout\TNTSearchScoutServiceProvider::class,` to your providers array. It has to be AFTER scout service provider
