### ISSUE TITLE
Does it not support paginate? 

### ISSUE THREAD

**Issue by 9IPHP** [teamtnt/laravel-scout-tntsearch-driver#8]
<img width="545" alt="2016-08-24 3 39 14" src="https://cloud.githubusercontent.com/assets/5997084/17922293/d633069c-6a10-11e6-9616-8f5507120062.png">
<img width="537" alt="2016-08-24 3 39 27" src="https://cloud.githubusercontent.com/assets/5997084/17922294/d65c55e2-6a10-11e6-95cf-d02b5481695b.png">
<img width="528" alt="2016-08-24 3 39 38" src="https://cloud.githubusercontent.com/assets/5997084/17922295/d665d298-6a10-11e6-8b03-16120a18a817.png">

I got the same result in different page.

**Comment by nticaric** [comment]
The pagination should work fine in version v1.0.8
