### ISSUE TITLE
Searching an empty collection produces fatal error.

### ISSUE THREAD

**Issue by fastmover** [teamtnt/laravel-scout-tntsearch-driver#80]
I'd like to have the functionality ready for when the model collection does get populated, but at the time being it's empty and throws a critical error if search is ran:

Whoops, looks like something went wrong.
1/1
IndexNotFoundException in TNTSearch.php line 65:
Index /var/www/site/storage/pages.index does not exist

**Comment by fastmover** [comment]
So it appears TNTSearch code doesn't allow for getting around the exception: IndexNotFoundException, maybe have a way to create an empty index file for empty models.

**Comment by nticaric** [comment]
Not sure how're getting this error because we have a check if the index exists or not

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L201

**Comment by fastmover** [comment]
The error is happening on a model search: Page::search($keywords)

**Comment by nticaric** [comment]
This has been fixed in v2.0.5
