### ISSUE TITLE
No search in non-english data

### ISSUE THREAD

**Issue by terion-name** [teamtnt/laravel-scout-tntsearch-driver#83]
Great and easy to setup package, thank you. 

But I have a problem.

I've indexed needed tables and when I test search, it works only over latin data, but not over cyrillyc (ukrainan, russian).

config is:
```php
'tntsearch' => [
        'storage'  => storage_path('indexes'),
        'charset' => 'utf8', // adding this didn't help
        'collation' => 'utf8_unicode_ci', // adding this didn't help
        'fuzziness' => env('TNTSEARCH_FUZZINESS', true),
        'fuzzy' => [
            'prefix_length' => 2,
            'max_expansions' => 50,
            'distance' => 2
        ],
        'asYouType' => true,
    ],
```

And also, how to use stemmers?

UPD:
Figured out, that it finds full string match, but does not substrings and fuzzy

**Comment by nticaric** [comment]
If you use the TNTSearch package directly without the scout wrapper, you'll be able to set different stemmers. Take a look at https://github.com/teamtnt/tntsearch

**Comment by gorlovka** [comment]
Not helpful...
