### ISSUE TITLE
Search optimization

### ISSUE THREAD

**Issue by BlitZ-UK** [teamtnt/laravel-scout-tntsearch-driver#87]
Hey! Great plugin, i have implemented it in a laravel project i'm working on, and i've indexed the data using tntsearch:import. It took in total pretty much bang on 1 hour to do **2494456** rows, which was impressive compared to the vanilla scout import command. 
The model that i'm using is a Product and has many columns in the MySQL database, however, i've stored in the search index only the ID and the name for now (using toSearchableArray on the model)

However, speed is intermittently faster/slower when testing it out. Some strings i try come back quickly, and more complex words come back slower, usually the longer the product name is (and more complex, like alphanumeric) the slower it'll be.

Luckily it's still way quicker than plain MySQL text search. Is there anything i can do to speed it up even more though? I assumed that indexing only them two columns should be quick enough, i've not changed any of the default config settings for tntsearch either. For example on timings
"HP Pavilion 15-au076sa" 6seconds on average (quite slow)
"Hayfever Tablets" 200milliseconds on average (perfect!)

Hopefully i've included as much information about this as i can that could be useful, hopefully also the import statistic is useful to you guys as i couldn't find any import statistics (from people using using tntsearch:import) in the github issues!
Any tips on how to make these searches any faster on the product name?

Also, is there anyway to only return certain columns from the model when using ::search? At the moment it takes everything, which i think could be slowing it down a little bit too on complex products (like having long descriptions) I tried select and pluck but to no avail. Would this be a factor in slowing it down? Just a thought.

Thanks!

**Comment by nticaric** [comment]
We're glad that you like the package. I can only suspect where the bottleneck lies so lets first do some trial and error.

So you say that "HP Pavilion 15-au076sa" takes about 6 seconds, what about this query:

`"HP Pavilion au076sa"`

How long does this take? Notice that the numeric part has been removed

**Comment by BlitZ-UK** [comment]
Hi @nticaric,

I couldn't tell that it made a difference, timing on subsequent same searches get much quicker so i also changed the string to a different one to test. I'm not sure if that's from the framework (laravel), or tntsearch, or the database itself caching things.

**Comment by nticaric** [comment]
What I wanted to know if the search is quicker if it doesn't contain numbers? Can you test this somehow?

**Comment by BlitZ-UK** [comment]
Sorry, i've updated my previous post, it's faster without

**Comment by BlitZ-UK** [comment]
To eliminate any of my app-specific things affecting loading speeds, i even created a new route with the following code i managed to find:
```
$tnt = new TNTSearch();
$driver = config('database.default');
$config = config('scout.tntsearch') + config("database.connections.$driver");

$tnt->loadConfig($config);
//$tnt->setDatabaseHandle(app('db')->connection()->getPdo());

$tnt->selectIndex("products.index");

$searchTerm = urldecode( $request->get( 'query' ) );

$res = $tnt->search($searchTerm, 12);

print_r($res);
```

Which also results with the pattern of when searching the same term over and over results in getting returned quicker the more it's searched.

**Comment by nticaric** [comment]
What is the speedup factor when using a number in the search query vs not using a number.

Since this is a products table, the words don't come in different forms, so a stemmer isn't necessary.  I'll help you to write an import command that should be 30-50% faster than the scout one.  Stay tuned, writing it

**Comment by BlitZ-UK** [comment]
The speedup when testing ranges from i'd say 35-50% it's hard to tell with the weird caching that i've outlined is going on.

And thanks for your help on this !

**Comment by nticaric** [comment]
Let's first start by creating a new command

`php artisan make:command IndexProducts`

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use TeamTNT\TNTSearch\TNTSearch;

class IndexProducts extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'index:products';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Indexes the products table';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->info("Indexing the products table");

        $tnt = new TNTSearch();
        $driver = config('database.default');
        $config = config('scout.tntsearch') + config("database.connections.$driver");

        $tnt->loadConfig($config);
        $tnt->setDatabaseHandle(app('db')->connection()->getPdo());
                
        $indexer = $tnt->createIndex('products.index');
        $indexer->query('select id, name from products;');
        $indexer->setLanguage('no');
        $indexer->run();

        echo "real: ".(memory_get_peak_usage(true)/1024/1024)." MiB\n\n";
    }
}
```

Don't forget to, register the command in Kernel.php and than run it with

`php artisan index:products`

The indexing should be match faster since stemming isn't necessary for your case

**Comment by BlitZ-UK** [comment]
Okay i've left that command to run, i'll let you know how it goes on when it's finished, thanks for your help with this anyway @nticaric much appreciated.

What is stemming by the way?

**Comment by nticaric** [comment]
Ok, let me know how long it takes without the stemmer.

Here's a quote of one of my previous answers

> The behavior that you're experiencing is because of the stemming process. The index actually doesn't contain the real words but a stemmed version of them, which we call terms. To put it simple, if you have the word runningit will be stemmed to run, if you have the word lazy it will be stemmed to lazi. It tries to find a common root of each word based on a stemming algorithm. The default one is Porter stemmer. The stemming process is necessary in order to give you correct results when you don't know the right word form upfront. So if you search for the word consolidate it will return documents that have consolidate, consolidated or consolidating in it because the stemmed version of all of the is consolid. So far so good, back to your example.

**Comment by BlitZ-UK** [comment]
Ah! That would explain what i was seeing inside the index file then, loads of simular terms for loads of different words, but yeah that's correct i won't be needing them. Thanks !

**Comment by nticaric** [comment]
This should also help a little bit with the search execution time. But lets see how much it improves it

**Comment by nticaric** [comment]
Another thing that would help is to write a custom tokenizer that would break the product name only by spaces. This should drastically improve the search execution. I guess the products don't have any weird characters inside, so this should be safe?

**Comment by BlitZ-UK** [comment]
Weird characters as in? It should just be alphanumeric, a few quotes and dashes here and there, i'll be sure to test the speed once it's all done!

**Comment by nticaric** [comment]
Weird characters could be non printable ones, but I guess you don't have them, everything else is fine. I'll help you write a new tokenizer

**Comment by nticaric** [comment]
Here's the process for a custom tokenizer. First you create a class

```php

<?php

class SplitBySpaceTokenizer implements TokenizerInterface
{

    public function tokenize($text)
    {
        return preg_split('/\s+/', mb_strtolower($text));
    }
}
```

namespace it properly, save it somewhere and do `composer du`. Your indexer command will now look like this:

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use TeamTNT\TNTSearch\TNTSearch;

class IndexProducts extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'index:products';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Indexes the products table';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->info("Indexing the products table");

        $tnt = new TNTSearch();
        $driver = config('database.default');
        $config = config('scout.tntsearch') + config("database.connections.$driver");

        $tnt->loadConfig($config);
        $tnt->setDatabaseHandle(app('db')->connection()->getPdo());
                
        $indexer = $tnt->createIndex('products.index');
        $indexer->query('select id, name from products;');
        $indexer->setLanguage('no');
        $indexer->setTokenizer(new SplitBySpaceTokenizer);
        $indexer->run();

        echo "real: ".(memory_get_peak_usage(true)/1024/1024)." MiB\n\n";
    }
}
```

Your search code will look like this:

```php
$tnt = new TNTSearch();
$driver = config('database.default');
$config = config('scout.tntsearch') + config("database.connections.$driver");

$tnt->loadConfig($config);
//$tnt->setDatabaseHandle(app('db')->connection()->getPdo());

$tnt->selectIndex("products.index");

$searchTerm = urldecode( $request->get( 'query' ) );

$tnt->setTokenizer(new SplitBySpaceTokenizer);
$res = $tnt->search($searchTerm, 12);

print_r($res);
```

**Comment by BlitZ-UK** [comment]
Hi @nticaric,

Thanks for your help yesterday. I have made the changes you've suggested and i can confirm that most search do come back quicker, however, some searches are coming back still after like 5 for terms like mentioned above, is this just the drawback of using it with 2.4m products?

Thanks!

**Comment by stokic** [comment]
@BlitZ-UK would it be possible for you to share your data with us (privately of course) so that we can run test/simulations?

**Comment by BlitZ-UK** [comment]
Hi @stokic, i'll send over the products dump.

Thanks

**Comment by nticaric** [comment]
@BlitZ-UK you can send the dump to info@tntstudio.hr

**Comment by aliocee01** [comment]
Hello,

Great to see information retrieval on display, nice work.

 @nticaric how can pagination be achieved using the optimize search query?



Many thanks

**Comment by spacemudd** [comment]
Was there any resolution to this?

My table is similar to OP where we've got values to search such as 'PURCHASE-ORDER-2018-018273', 'DELL-XC82618-11'.

**Comment by BlitZ-UK** [comment]
I ended up using a self hosted solution like Elasticsearch or Sphinx instead, so I can’t really comment on the status of this any longer. However, the package is great and very helpful developers behind it who where willing to help resolve these type of issues.

**Comment by thewebartisan7** [comment]
So great package that you move to other hosted solution? :( a bit sad to read such experience
