### ISSUE TITLE
Error: Unable to open database file

### ISSUE THREAD

**Issue by SFPink** [teamtnt/laravel-scout-tntsearch-driver#89]
Hello,

Trying to test this plugin out on my project but I am getting this error:

SQLSTATE[HY000] [14] unable to open database file

I was following this tutorial https://laravel-news.com/tntsearch-with-laravel-scout to give you an idea of what I've done so far. Have I missed something?

Regards

**Comment by the94air** [comment]
In witch step does it give you the error?

**Comment by SFPink** [comment]
Sorry I forgot that bit.

When I run the import: php artisan tntsearch: import "App\MyModel"

**Comment by the94air** [comment]
Are you using SQLlite database ?

**Comment by the94air** [comment]
Are you using SQLlite database?

**Comment by SFPink** [comment]
No, I'm using Postgres. Is this not supported?

**Comment by stokic** [comment]
Check if the file defined in your
`'tntsearch' => [
    'storage'  => storage_path(),
],`

is readable/writable...

**Comment by SFPink** [comment]
Oh.. It was actually a pretty stupid mistake I had this in my config:

'tntsearch' => [ 'storage' => storage_path('/index'), ],

Index doesn't exist, It works now thanks.

**Comment by Hadi-Abedzadeh** [comment]
I had same problem but this way worked for me: Create `search` directory in `storage` path
