### ISSUE TITLE
Best way to limit results

### ISSUE THREAD

**Issue by SFPink** [teamtnt/laravel-scout-tntsearch-driver#91]
What is the best way to limit results?

I know I can do this: 
`Model::search($term)->get()->take(300)`

However this couldn't be the best method as it's retrieves everything then takes what needed.

I tried this:
`Model::search($term, 300)->get()`

But it complains about 300 being an invalid callback so I'm assuming it's not possible this way.

Regards

**Comment by SFPink** [comment]
For now I've created my own trait for my model that uses the TNTSearch directly. This way I can create my own search function with a limit parameter.

**Comment by kenzouno1** [comment]
It will be great when you share your code.

**Comment by SFPink** [comment]
I haven't looked at this code in a while but here is the trait I created. Simply add the trait to a model, this will allow you to do something like this Model::searchByTerm("test", 10)

`
<?php

namespace App\Traits;

use TeamTNT\TNTSearch\TNTSearch;
use TeamTNT\TNTSearch\TNTGeoSearch;

trait Searchable
{
    public static function searchByTerm($term, $limit = 100){
        $self = new static();
        $tnt = new TNTSearch;

        //Database Connection
        $driver = config('database.default');
       //Reference tnt & connection config
        $config = config('scout.tntsearch') + config("database.connections.$driver");

        $tnt->loadConfig($config);
        $tnt->setDatabaseHandle(app('db')->connection()->getPdo());

        $tnt->selectIndex($self->searchableAs() . ".index");

        $res = $tnt->search($term, $limit);

        $keys = collect($res['ids'])->values()->all();

        $results = $self::active()->whereIn('id', $keys)->get();

        return $results;
    }

}
`

**Comment by juehai** [comment]
You don't have to write your own trait as Scout will pass limit number to TNTSearch.

I believe that you should call take() before you execute get() because according to the source of Scout\Builder, the function take will pass limit number to TNTSearch.

```
    // vendor/laravel/scout/src/Builder.php
    /**
     * Set the "limit" for the search query.
     *
     * @param  int  $limit
     * @return $this
     */
    public function take($limit)
    {
        $this->limit = $limit;

        return $this;
    }



    // vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php
    /**
     * Perform the given search on the engine.
     *
     * @param Builder $builder
     *
     * @return mixed
     */
    protected function performSearch(Builder $builder, array $options = [])
    {
        $index = $builder->index ?: $builder->model->searchableAs();
        $limit = $builder->limit ?: 10000;
        $this->tnt->selectIndex("{$index}.index");

        $this->builder = $builder;
        $this->tnt->asYouType = $builder->model->asYouType ?: false;

        if ($builder->callback) {
            return call_user_func(
                $builder->callback,
                $this->tnt,
                $builder->query,
                $options
            );
        }
        if (isset($this->tnt->config['searchBoolean']) ? $this->tnt->config['searchBoolean'] : false) {
            return $this->tnt->searchBoolean($builder->query, $limit);
        } else {
            return $this->tnt->search($builder->query, $limit);
        }
    }
```
