### ISSUE TITLE
Search using a wildcard to match everything and after that add filters

### ISSUE THREAD

**Issue by joelarmad** [teamtnt/laravel-scout-tntsearch-driver#93]
He, I need to do something like this:
```
App\MyModel::search('*')
    ->where('id', 1)
    ->get();
```
Is this possible? which is the better way to do it? Thanks in advance...

**Comment by nticaric** [comment]
Thats easy, you don't need the search in this case

`$models = App\MyModel::where('id', 1)->get();`

**Comment by joelarmad** [comment]
Sorry, that was just a basic example I need something like:
```
app\MyModel::search('*')
    ->where('name', 'Joel')
    ->where('date', '>=', '12-02-1990')
    ->where('city', 'London')
    ->get();
```

**Comment by joelarmad** [comment]
Any idea? Is that possible or not? Thanks in advance.

**Comment by nticaric** [comment]
From your example it's seems that a `where` should be enough

```php
App\MyModel::where('name', 'Joel')
    ->where('date', '>=', '12-02-1990')
    ->where('city', 'London')
    ->get();

**Comment by joelarmad** [comment]
I´m looking for registers in the elasticsearch index. In my case 'name', 'city' and 'date' are fields of my index not attributes from my class. Sorry if I was not enough clear.

**Comment by joelarmad** [comment]
@nticaric  I´m not sure that you understand what I´m trying to do but for me is enough if I can make some raw query to elastic index. Is it that possible using this driver? Thanks in advance.

**Comment by nticaric** [comment]
@joelarmad I guess not, the driver is only a wrapper around tntsearch.
