### ISSUE TITLE
Laravel Scout with tntsearch returns empty array

### ISSUE THREAD

**Issue by maranovot** [teamtnt/laravel-scout-tntsearch-driver#94]
Hey, I have set up Laravel Scout with tntsearch according to the documentation. Only thing I did on top was that I set up database queue driver. When I try to search a model with the ::search all I get is empty array.

Controller test function:

```
public function test()
    {
        $search = Store::search('test')->get();
        return view('test')->with('search', $search);
    }
```

Store model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;

class Store extends Model
{
    use SoftDeletes;

    use Searchable;

    protected $dates = ['deleted_at'];

    protected $fillable = ['name', 'url', 'contact', 'description', 'detail', 'featured', 'network_id', 'currency_id',
        'link', 'comment', 'category_id'];

    protected $with = ['favoritable'];

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array = $this->toArray();

        // Customize array...

        return $array;
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function network()
    {
        return $this->belongsTo('App\Network');
    }

    public function currency()
    {
        return $this->belongsTo('App\Currency');
    }

    public function favoritable()
    {
        return $this->belongsTo('App\Favoritable', 'favoritable_id', 'favoritable_id');
    }
}

```

the result is :
```
[ ]
```
Do you know what can cause this.

**Comment by stokic** [comment]
May be a silly question but did you index your model? :)

**Comment by maranovot** [comment]
Yes I did it with the scout:import command and I can see the store.index in my storage folder

**Comment by joelarmad** [comment]
He, put something in your array just to try, something like:
```
public function toSearchableArray()
    {
        $array = Array();
        $array['name'] = $this->name;
        $array['description'] = $this->description;
        $array['url'] = $this->url;
      
        return $array;
    }
```
And now look for something that you are totally sure that is indexed, like some name. Let´s see what the search returns now.

**Comment by maranovot** [comment]
@joelarmad I did what you suggested but still the result is empty array. My stores table contains only one store with the name 'test' so there is no way to miss on my end. Maybe the stores aren't indexed? How should the stores.index file look like?

**Comment by stokic** [comment]
Index is just a sqlite database so open it up in your sql viewer tool and
check if there is really there :)

**Comment by joelarmad** [comment]
Let´s put some foo data:
```
public function toSearchableArray()
    {
        $array = Array();
        $array['name'] = 'Maranotov';
        $array['description'] = 'My foo data';
        $array['url'] = 'www.mysite.com';
          
        return $array;
    }
``` 
If is not installed install tinker and using it search in your index and let's see what happens:
php artisan tinker
 App\Store::search('Maranotov')->get();

**Comment by maranovot** [comment]
Ok, so I don't know why but indexing with scout:import command doesn't work but the tntsearch:import does work. So when using tntsearch:import command everything works perfectly.

**Comment by nticaric** [comment]
@maranovot you mentioned that you queued the indexing, which means you need to run `php artisan queue:work` to actually do the indexing process

**Comment by maranovot** [comment]
Ok, so I did ```php artisan tntsearch:import App\\Store``` then I did the ```php artisan queue:work```. And it seems to be working now, the ```return $this->toArray()``` is also working.

**Comment by nticaric** [comment]
Glad it works
